### ISSUE TITLE
Deploy only part of repo

### ISSUE THREAD

**Issue by addatwork** [banago/PHPloy#100]
I don't know if the current version has any solution for my case, if so, please advise.
The current structure is something like:

/dir1/
/dir2/
file

I want to deploy only the contents of the /dir1/ to the /public_html/ of a server. Can this be done? 
Great tool btw. Thank you.

**Comment by banago** [comment]
@addatwork yes this can be done very easily. All you have to do is ignore the rest of the files/folders by using the `skip[]` command. Please refer to the example `deploy.ini` file for a concrete example. Happy deployment!
