### ISSUE TITLE
Empty directory not removed from server

### ISSUE THREAD

**Issue by rzds** [banago/PHPloy#103]
If you make a commit after you remove some directory (containing files) and you deploy that to the server, you will notice that the directory still exists on the server and the files are gone.
I think it should delete the directory too.

**Comment by banago** [comment]
@rzds yes it should delete the directory too. I'll look into this too. Thanks for pointing it  out.

**Comment by banago** [comment]
Seems we ran unto a won't-fix here. Git won't track empty directories and by extension even care if you deleted a directory or not - it just cares about the files: http://stackoverflow.com/a/10075480/512277

**Comment by banago** [comment]
@rzds, I build a custom check for this since Git won't care. Will push shortly.

**Comment by rzds** [comment]
Yes. This is what I was thinking. When PHPloy removes some files from a directory, a quick check to see if the directory is empty. If empty, you can safely remove it.
Thanks!
