### ISSUE TITLE
Oh Snap: Could not upload file

### ISSUE THREAD

**Issue by AngelinDark** [banago/PHPloy#104]
I'm trying to do a deploy, but for any reason the command returns this error.

PHP Warning:  ftp_fput(): Can't open that file: Is a directory in phar:///usr/local/bin/phploy/vendor/banago/bridge/src/Backend/Ftp.php on line 140

Any idea what might be causing this error?

**Comment by banago** [comment]
@AngelinDark there is a file with the name of the directory you are trying to upload to that causes this error. Right now you will have to login to your server and delete that file manually.
