### ISSUE TITLE
Absolute path to deploy.ini file.

### ISSUE THREAD

**Issue by craftpip** [banago/PHPloy#105]
Hello, I have a team working on the same repo, as the deploy.ini is in the same repo, everyone gets the ftp server's credentials, 
Is there a way to move deploy.ini out of the repo, and give a absolute path to the ini file while executing phploy.phar ?

BTW, PHPloy is working great !
Thanks.

**Comment by banago** [comment]
@craftpip the roud is paved for that but it's not implemented fully yet. I'll make sure I do. Thanks for pointing it out.

**Comment by banago** [comment]
@craftpip what you could do in this case, is ignore `deploy.ini` so Git won't move it around and each guy can have their own version. It would be the same result as having it somewhere else outside the repo, right?
