### ISSUE TITLE
Fails when deleting a file that does not exist on remote

### ISSUE THREAD

**Issue by NathanGiesbrecht** [banago/PHPloy#106]
When deleting files from the repository, if the files do not exist on the deployment server, PHPloy will fail. I think this should probably throw a warning, but an error I think is the wrong course of action, since the file that is to be deleted has already been deleted. Or is there some other reason for this behaviour? In my case, I'd deleted a file from production servers that were a security issue, then when I delete from the repository and try to deploy changes later, I have to go and add the files on the server before the PHPloy deployment will run successfully by deleting them.

**Comment by banago** [comment]
@NathanGiesbrecht I've had this issue several times too. This is how [Brige](https://github.com/banago/Bridge) handles fails and PHPloy will catch it and stop the execution. I hope this will be fixed on PHPloy 4.

**Comment by banago** [comment]
@NathanGiesbrecht this is now fixed by a contribution from @craftpip.

**Comment by NathanGiesbrecht** [comment]
Wonderful! Thanks @craftpip
