### ISSUE TITLE
command phploy don't work

### ISSUE THREAD

**Issue by strauss69400** [banago/PHPloy#107]
hello,

i use a virtual machine with debian 7.5
when i copy the phploy.phar in /usr/local/bin, the command "phploy" don't work in the terminal.

maybe, i forgot something to do?

sorry for my english

**Comment by craftpip** [comment]
Run it with the .phar extension, and it should work.

**Comment by strauss69400** [comment]
Thanks for your help.

It s strange that my debian do not know the command phploy.
Do you have already this problem?

**Comment by craftpip** [comment]
Yes, i had the same problem.
adding .phar was not a problem. :)

**Comment by strauss69400** [comment]
ok thanks.it works on linux.

but on windows, impossible to do.i use composer to install dependencies but when i launched the command "phploy" in git-bash, it don't work.
in my system-path, i add c:\wamp\www\PHPloy

**Comment by desertknight** [comment]
Just edit __phploy.bat__ with 
`php C:\Some\Directory\Where\Install\PHPloy\bin\phploy.phar %*`
