### ISSUE TITLE
Oh Snap:Scheme in not defined

### ISSUE THREAD

**Issue by strauss69400** [banago/PHPloy#108]
hello,

I managed to install phploy on windows and linux.
so I put in the root of my project the deploy.ini file.

but when I run the command "phploy" I have this error:
Oh Snap:Scheme in not defined...

i don't understant why i get this error.
my file
[staging]
    scheme = ftp
    user = user1
    pass = *****
    host = acme.fr
    path = /sites/myproject
    port = 21

thank you for your help

**Comment by craftpip** [comment]
I don't know the real cause of this error,

You can specify the servers to deploy,
`phploy.phar -s staging`, 
I hope it works.

**Comment by strauss69400** [comment]
thanks for your help

but i have the same error.
i don't understand why i get this error.it 's really strange!!

**Comment by strauss69400** [comment]
i found the problem.
there is a slash in my password,the function url_parse don't worked.
