### ISSUE TITLE
bug ftp_mkdir 

### ISSUE THREAD

**Issue by strauss69400** [banago/PHPloy#109]
hello,
when i try my symfony project, phploy bug when a folder contains a file which the name of the file to begin with a point like .gitkeep
is there a solution for this problem?

thank you

**Comment by banago** [comment]
Theoretically this should not happen. I haven't run into this problem, but I'll file this as a bug. I hope this will be solved soon.

Thanks for reporting it @strauss69400!

**Comment by banago** [comment]
Hi @strauss69400, 

I tested this issue on several servers. It works fine - directory and file were created ok. One one server, the file starting with a dot was deleted by the server immediately after upload. And this seems a server configuration issue. 

Please get in touch with your host about this. If you still feel this is a PHPloy related issue, please re-open this ticket and give us some more info about the error showing on your screen. Thanks.
