### ISSUE TITLE
Installation not clear

### ISSUE THREAD

**Issue by owenkavanagh** [banago/PHPloy#112]
I'm reading through the read me and it's not clear what to do with all of the files.

I know where to put the .ini file and .phar file but where should I put the other files from the root and the src folder?

**Comment by banago** [comment]
@owenkavanagh thanks very much for opening this issue. I'll make sure I clarify this on the `readme` over the weekend. But basically, what you have to do is get the file that is in the `bin` folder and use only that. You can put that in your project or in a global place at `/usr/local/bin/`, if you are using a Mac or Linux machine.
