### ISSUE TITLE
.revision file appears on the server but entire repository uploading

### ISSUE THREAD

**Issue by ElementalWebD** [banago/PHPloy#114]
Hi,

Great script and I am using it across a number of sites. I am having trouble with one particular site which appears to be ignoring the .revision file. I have attempted to run the --sync command and deleted and replaced the .revision file a number of time but with no luck. Was wondering if this was something other people have come across?

Thanks

**Comment by banago** [comment]
@ElementalWebD I've had the same issue with one server too. I think it was a windows server and very restricted in setup. Now that I know someone else has had the same issue, I'll look into it further. Thanks for opening the issue.

**Comment by banago** [comment]
@ElementalWebD This seems an issue at server level how they handle dot files. Unfortunately I don't have any more access to that server where I experienced the same issue. I'll have to close this issue for now. If more people report this, I'll have to did deeper then. Good luck!
