### ISSUE TITLE
Question: Multiple deploy.ini sections defined, none specified?

### ISSUE THREAD

**Issue by bobrocke** [banago/PHPloy#119]
If I have a `deploy.ini` file with multiple sections for multiple servers, but none are specified in the launch command, `phploy` for example, do all sections get executed? Only the first?

What is the best way to protect from an inadvertent `phploy` when it should be called with the section name.

For example `phploy staging` might be intended, but if just `phploy` is used, will both staging and production be updated?

**Comment by banago** [comment]
If your servers have custom names like `staging`, `production`, then all are deployed to. 

To only deploy to one server by default, you have to name that one `default` and use `--all` flag to deploy to all servers when you need to. Please refer to issue #99 for more on this.

**Comment by bobrocke** [comment]
OK. For safety sake, I've configured the least dangerous to deploy to by accident server as `[default]` and then again by the name I want to reference it by. That way, if I accidentally just use `phploy` I won't mess up the `[production]` server.
