### ISSUE TITLE
Invalid symmetric difference expression error

### ISSUE THREAD

**Issue by bobrocke** [banago/PHPloy#122]
With submodules and changes to be deployed in user/themes/materialize, I get an `Invalid symmetric difference` error:

 ```
RockBox:www.grav.dev bob$ phploy --submodules

---------------------------------------------------
|              PHPloy v3.0.19-stable              |
---------------------------------------------------

Scanning repository...
   Found 2 submodules.
   Found submodule user/plugins/materializer.
      Scanning for sub-submodules...
   Found submodule user/themes/materialize.
      Scanning for sub-submodules...

SERVER: production
   No files to upload.

SUBMODULE: user/plugins/materializer
fatal: Invalid symmetric difference expression e23ca4f9c87afafbdf153b9fe6e76dc660a25e07...HEAD
   No files to upload.

SUBMODULE: user/themes/materialize
fatal: Invalid symmetric difference expression e23ca4f9c87afafbdf153b9fe6e76dc660a25e07...HEAD
   No files to upload.

----------------[ 0.00B Deployed ]----------------
```

**Comment by banago** [comment]
Yep, some other guys reported this. I'll check this too over the weekend.
Seems like an issue I've caused.

**Comment by banago** [comment]
@bobrocke this is finally fixed - thanks for your patience. To make it work, you will have to manually delete the `.revision` file from the deployed submodules in your server, since that contains the wrong revision, basically the parent repo revision. Please let me know how it goes. Happy deploying!

**Comment by bobrocke** [comment]
I no longer get the error, but `phploy -s production --submodule` does not replace the submodule `.revision` files that I deleted, nor upload changes to those submodules.

**Comment by banago** [comment]
@bobrocke you need to use `--submodules` in plural. I had to test it to find out too - subtle difference :smile:

**Comment by bobrocke** [comment]
Yep. `--submodules` fixed me right up. Thanks! It's working well now.
