### ISSUE TITLE
phploy.phar is replacing my root vendor/composer directory with it's own vendor/composer

### ISSUE THREAD

**Issue by kidcodist** [banago/PHPloy#124]
Whenever I deploy it seems like my root's vendor/composer directory get's overwritten with phploy.phar's own vendor/composer directory. I first tried locally, phploy.phar in the root of my project, then I tried globally, from /usr/local/bin both had the same outcome.

**Comment by banago** [comment]
@didierstockmans that's very strange. The `.phar` file is archived and it does not spit files anywhere. How are you installing it?

**Comment by didierstockmans** [comment]
I just downloaded it from github and copied the phploy.phar from the bin directory to my project root.

**Comment by banago** [comment]
You have done that correctly. What system are you on?

**Comment by didierstockmans** [comment]
I'm on Mac Yosemite.

**Comment by banago** [comment]
Great.

I have never experienced this. My best guess is that your PHAR is
configured badly. Can you have a look at your php.ini file (the cli one)
and see what's going on there for PHAR?

**Comment by didierstockmans** [comment]
Apparently there wasn’t a php.ini file configured for cli. I copied the php.ini.default. 
The settings for phar are: 

Phar: PHP Archive support => enabled
Phar EXT version => 2.0.2
Phar API version => 1.1.1
SVN revision => $Id: cc0fad28eb9ea42466f756c3b5fc22c764e32690 $
Phar-based phar archives => enabled
Tar-based phar archives => enabled
ZIP-based phar archives => enabled
gzip compression => enabled
bzip2 compression => enabled
OpenSSL support => enabled

Directive => Local Value => Master Value
phar.cache_list => no value => no value
phar.readonly => On => On
phar.require_hash => On => On

I downloaded the phar file again and tried locally and globally, still it replaces the composer folder.

Are my configurations correct?

**Comment by didierstockmans** [comment]
I just copied the whole source in my project and ran phploy.php. Everything went ok, so I guess it's probably something with the phar file.

**Comment by banago** [comment]
For sure, but it's a very strange one nonetheless. I've never had this
issue. I'm keeping this ticket around in case someone else will ran unto
the same issue. Thanks and happy deploying!

**Comment by stefanvangastel** [comment]
Same issue here. Deploying from and to Ubuntu 14.04 server with phploy.phar globally.

PHPloy replaces my remote vendor/composer dir... Thats weird right? my composer.json is untouched only the installed.json file seems to be changed.

**Comment by rvdborn** [comment]
Same issue.

Ubuntu 14.04 Cloned rep, installed bin/phploy.phar globally.
After uploading with -o flag to include vendor dir. All directories in vendor are uploaded properly, except for vendor/composer. Contents of the files are completely different.

Example:

autoload_psr4.php contains
```
return array(
    'Banago\\PHPloy\\' => array($baseDir . '/src'),
    'Banago\\Bridge\\' => array($vendorDir . '/banago/bridge/src'),
);
```

**Comment by ronvankesteren** [comment]
Same issue, also Ubuntu 14.04.

**Comment by banago** [comment]
Guys, I'm looking into this - thanks for reporting.

**Comment by banago** [comment]
@didierstockmans, @stefanvangastel, @rvdborn can you guys please grab latest version and run it to see if this is fixed? Thanks very much.

**Comment by banago** [comment]
@didierstockmans, @stefanvangastel, @rvdborn can you guys please grab latest version and run it to see if this is fixed? I run tests on my Laravel projects but I cannot reproduce this issue. Thanks.

**Comment by stefanvangastel** [comment]
Wil try asap

Op wo 19 aug. 2015 21:56 schreef Baki Goxhaj <notifications@github.com>:

**Comment by banago** [comment]
@fadion do you have any idea why this might happen?

**Comment by fadion** [comment]
@banago no idea. Never seen it happened and didn't find any reference online.

**Comment by banago** [comment]
@didierstockmans, @stefanvangastel, @rvdborn can you guys please grab latest version and run it to see if this is fixed? Thanks very much.
