### ISSUE TITLE
Extensibility - Symfony Console component

### ISSUE THREAD

**Issue by bsfsos** [banago/PHPloy#128]
Lets take phploy to the next level by using symfony console component.
This will not only make it extensible but also makes integration with any frameworks easy.
Please let me know your inputs.
Thanks

**Comment by banago** [comment]
@bsfsos yes, this is in the plans for v4. Would you like to contribute on this section? I would really appreciate it.

**Comment by bsfsos** [comment]
@banago Sure, I will.
