### ISSUE TITLE
In new version (3.1.0) --sync command send empty revision file on server.

### ISSUE THREAD

**Issue by kkraszy** [banago/PHPloy#130]

**Comment by banago** [comment]
Will check, thanks for reporting.

**Comment by kkraszy** [comment]
New reporting: after rollback revision file does not change.

**Comment by GaryJones** [comment]
Can confirm both of these.

* Expected `phploy --rollback` and `phploy --rollback=123` to update `.revision` with the relevant SHA, but it updates it with the SHA of the latest commit.
* Expected `phploy --sync` to update `.revision` with latest SHA, bit it leaves an empty file instead.

**Comment by GaryJones** [comment]
I think, during `deploy()`, the `setRevision()` is called, which reads from `->localRevision()`. However, that isn't set to the `currentRevision()` until `push()`, which happens after `setRevision()` is called.

If `setRevision()` started with:
~~~php
$localRevision = $this->currentRevision();
~~~
then it may solve both problems (untested).

**Comment by banago** [comment]
@kkraszy this is now fixed. Thanks for reporting it and for using PHPloy. @GaryJones thanks for your contribution - really appreciated.
