### ISSUE TITLE
Force mode

### ISSUE THREAD

**Issue by vytenizs** [banago/PHPloy#131]
Should be good to have force mode to make deployment even if there are errors like purging files or smth, because now if purge folder is empty phploy throws errors. Still nasty that purge does not support regex. For example if I want to purge only *.php php files and leave others untouched.

**Comment by banago** [comment]
@vytenizs would you like to contribute this feature? I'd be happy to merge when ready.

**Comment by vytenizs** [comment]
Ofcourse i will look into it when ill have some free time. I love PHPloy its good for simple project :) Id love to contribute.

**Comment by banago** [comment]
@vytenizs I'll be looking forward to your contributing. Until then, I'm closing this issue so there aren't many pending. Thanks.
