### ISSUE TITLE
Didn't read the .revision file for some reason

### ISSUE THREAD

**Issue by addatwork** [banago/PHPloy#132]
Could not reproduce, but:
- deployed in list mode, everything was ok
- deployed in normal mode: "No revision found. Fresh deployment - grab a coffee"
- killed the execution
- checked the revision file via ssh, was there and not empty
- deployed in list mode again, fine
- deployed in normal mode, worked as expected.

Needless to say, that was in production. Crapped my pants a little.

**Comment by JayBizzle** [comment]
Perhaps if no revision is found on the server, the user should be prompted to confirm they want to upload everything!?

**Comment by AngelinDark** [comment]
Same for me.

**Comment by banago** [comment]
This happens sometimes due to internet connection issues. It has happened to me too and I've done the same - kill the process and re-run.
