### ISSUE TITLE
Oh snap: ssh2 PECL extenstion is not installed. Please install it to use ssh.

### ISSUE THREAD

**Issue by KhaOmni** [banago/PHPloy#138]
I'm using sftp so I don't have to get this error !!

Thanks in advance :)

**Comment by peterbrinck** [comment]
You do get that error because you're using SFTP
On Linux based system, you can install SSH2 with this:
``` sudo apt-get install libssh2-php ```

**Comment by KhaOmni** [comment]
I have no acces to the server via SSH mode. 
I think, the developper of this plugin should mention this in requirements section.

**Comment by peterbrinck** [comment]
He should mention that the SSH2 extenstion is needed

But can't you just use normal FTP then?

**Comment by KhaOmni** [comment]
Unfortunately, it's not possible. I can only with SFTP
Do you now another plugin that ddo the same work as PHPloy ?
I was working with Dploy, but it contains a lot of bugs and it's no longer maintained for a while

**Comment by peterbrinck** [comment]
The developer himself used to use these two:
https://github.com/git-ftp/git-ftp
https://github.com/BrunoDeBarros/git-deploy-php

I've not tried any of them

**Comment by KhaOmni** [comment]
Thanks very much
I have tested git-deploy-php and have found out that SSH2 is needed again.

**Comment by peterbrinck** [comment]
Even if you just use normal FTP?

**Comment by KhaOmni** [comment]
The server doesn't allow it

**Comment by oxodesign** [comment]
@KhaOmni you know you can run PHPLoy from your dev machine/computer, no need to use it on the server, since you can't install SSH2 on it.

**Comment by KhaOmni** [comment]
@oxodesign  is there any special config that I have to do ?

My deploy.ini file contains:
[dev]
scheme = sftp
user = ********
pass = ********
host = ********
path = /htdocs
port = 22
passive = true


When I run "php phploy.phar" on my local machine, I get the error:
Oh snap: ssh2 PECL extenstion is not installed. Please install it to use ssh.

Thank you

**Comment by oxodesign** [comment]
You have to install SSH2, the installation is a little different depending on your OS, @peterbrinck told you how to install it on Linux, google it for Windows!

**Comment by banago** [comment]
@KhaOmni sorry for the inconvenience. All you have to do at this point is install SSH2 PECL extension locally on your computer (not on the server). What OS are you using?
