### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by martin-sucha** [banago/PHPloy#142]
Please add guidelines for contributors into [CONTRIBUTING.md](https://github.com/blog/1184-contributing-guidelines) that will explain at least:

* The coding style
* Who and when should generate `bin/PHPloy.phar` (btw maybe the generated archive should be attached to a release in GitHub, instead of being commited to the repository?) When #76 is fixed, this should just mention that the archive is automatically generated for releases.

**Comment by banago** [comment]
:+1:

**Comment by banago** [comment]
@martin-sucha please add anything you see fit to the contributing file. Thanks.
