### ISSUE TITLE
Can you please submit this package to packagist?

### ISSUE THREAD

**Issue by Ilyes512** [banago/PHPloy#143]
This package is not submitted to packagist? You can do that here https://packagist.org/packages/submit

**Comment by banago** [comment]
On the roadmap, but seems I'll do that sooner then planned. Thanks for opening the issue.

**Comment by Ilyes512** [comment]
:+1:  Tnx

**Comment by banago** [comment]
PHPloy is now on Packagist as a composer package: https://packagist.org/packages/banago/phploy
