### ISSUE TITLE
fatal: Invalid symmetric difference expression

### ISSUE THREAD

**Issue by elzette** [banago/PHPloy#144]
It's been great using PHPloy. I've used the same settings successfully for a number of repositories. Now with the same set up for some reason on a new I keep on getting 

fatal: Invalid symmetric difference expression withnumbers...HEAD

I've read in a previous comment to delete .revision file, but this is at the first deployment, there is no revision file.

Do you have any idea what could be causing this?

**Comment by banago** [comment]
@elzette I don't know actually what might be causing it. Can you please grab the latest version and do another test? After that I can do some more digging. Thanks for using PHPloy.

**Comment by banago** [comment]
@elzette this should now be fixed. Thanks for using PHPloy.
