### ISSUE TITLE
Global installation cannot change to paths with spaces

### ISSUE THREAD

**Issue by hellodaniel** [banago/PHPloy#145]
Deploying a project with a space in the path causes fatal error. I'm fairly sure this is an issue - happy to be corrected! Example output: 

	MBP15-2:html daniel$ pwd
	/Users/daniel/Sites/Clients/Project with spaces/html
	
	MBP15-2:html daniel$ phploy

	---------------------------------------------------
	|              PHPloy v3.2.0-stable              |
	---------------------------------------------------

	fatal: Cannot change to '/Users/daniel/Sites/Clients/Project': No such file or directory
	|----[ No revision found. Fresh deployment - grab a coffee ]----|
	fatal: Cannot change to '/Users/daniel/Sites/Clients/Project': No such file or directory

	SERVER: staging
	fatal: Cannot change to '/Users/daniel/Sites/Clients/Project': No such file or directory
	PHP Notice:  Undefined offset: 0 in phar:///Users/daniel/.bin/phploy3/src/PHPloy.php on line 287
	fatal: Cannot change to '/Users/daniel/Sites/Clients/Project': No such file or directory
	PHP Notice:  Undefined offset: 0 in phar:///Users/daniel/.bin/phploy3/src/PHPloy.php on line 1061
  	No files to upload.
	
	----------------[ 0.00B Deployed ]----------------
	MBP15-2:html daniel$

**Comment by banago** [comment]
@hellodaniel seems like a bug. I have no idea how to fix it. Do you have any idea?

**Comment by banago** [comment]
@hellodaniel never mind - found end fixed. :smile:
