### ISSUE TITLE
Can't Deploy Using SSH

### ISSUE THREAD

**Issue by tubiz** [banago/PHPloy#150]
Pls I am using a Laravel Forge configured server and cant seems to connect via SSH.
I have entered my public and private key as well as the paypass but cant connect to no avail.

I keep getting this error  Could not login to 'xxx.xxx.xxx.xxx' as 'forge' using public key authentication

**Comment by banago** [comment]
@tubiz can you please try sftp and check if it works?

**Comment by tubiz** [comment]
@banago still  the same
This is the error am getting 
PHP Warning:  ssh2_auth_pubkey_file(): Authentication failed for forge using public key: Callback returned error in phar:///usr/local/bin/phploy/vendor/banago/bridge/src/Backend/Ssh2.php on line 72

**Comment by noahjohn9259** [comment]
I have the same issue on this.. Normally sftp connections i used only private key file without the public key using ftp client.

**Comment by banago** [comment]
I looked into this quite deep but cannot find a solution. I pinged @victorstanciu the original implementer of this. Let's hope he has a look into it.

**Comment by banago** [comment]
This is now fixed in version 4.0 that landed in master branch a bit ago.
