### ISSUE TITLE
Deprecated function split

### ISSUE THREAD

**Issue by ChrisWiegman** [banago/PHPloy#153]
Started seeing this during a deploy today:

Deprecated: Function split() is deprecated in phar:///.../PHPloy/bin/phploy.phar/src/PHPloy.php on line 1164
PHP Deprecated:  Function split() is deprecated in phar:///.../PHPloy/bin/phploy.phar/src/PHPloy.php on line 1164

Is this something you've already addressed?

**Comment by ChrisWiegman** [comment]
This looks like it was introduced in 3.5.0 the other day and also causes errant directory warnings by trying to remove non-empty directories.

**Comment by banago** [comment]
Yep, I used `split` in stead of `explode` in latest changes. Will fix, thanks @ChrisWiegman.
