### ISSUE TITLE
Error: Oh Snap: Unsupported git-diff status: .

### ISSUE THREAD

**Issue by hotrush** [banago/PHPloy#156]
I am running ```php phploy.phar -o``` and receive an error

```Oh Snap: Unsupported git-diff status: .```

Others here it's a vendor directory with composer dependencies.

What am i doing wrong?

Using PHPloy v3.5.1

**Comment by banago** [comment]
Seems like a bug, not your fault. Will look into it.

**Comment by hotrush** [comment]
Thanks

**Comment by Rhymond** [comment]
same here :/
Oh Snap: Unsupported git-diff status: .

**Comment by andresnijder** [comment]
+1

**Comment by mrksmts** [comment]
+1

**Comment by andresnijder** [comment]
When using -o, PHPloy::compare should not check on the status code, because the output does not contain a status code. Just a list of untracked files.
