### ISSUE TITLE
Option to upload specific, ignored file

### ISSUE THREAD

**Issue by sanderha** [banago/PHPloy#157]
The -o or --others function is great, but would it be possible to get a function for only one file/folder? I have a folder with components i want to upload, but it is gitignored. Would be great to be able to specify this folder and upload it. 

Maybe something like 
```
phploy -o /path/to/folder
```

**Comment by Eduruiz** [comment]
or a option on deploy.ini file.

in my case I have assets/ and dist/, the best will be not keep the dist/ folder out of version control, but I need to upload it if I made changes on things, so will be nice to have a something like `others[] = 'dist/'`

**Comment by andresnijder** [comment]
+1

**Comment by m4nolo** [comment]
+1

**Comment by banago** [comment]
Good news guys - this feature now landed on 4.0 branch: https://github.com/banago/PHPloy/commit/5e8f48ea2370884bdade22a47432d562e77fcc89

**Comment by banago** [comment]
Guys, this feature is now in master branch. Please check out the sample `phploy.ini` and look for the `include[]` lines.
