### ISSUE TITLE
Oh Snap: Cannot read SSH public key file:

### ISSUE THREAD

**Issue by vukanac** [banago/PHPloy#158]
I need to use PHPloy to deploy to simple ftp server on shared hosting.
I have commented out everything except `quickmode` as plain ftp option.
I get error from title with warning "`array_merge(): Argument 2 is not an array`", on PHPloy:504

**Comment by vukanac** [comment]
Writing test for this case would be nice start.

**Comment by banago** [comment]
@vukanac please follow this on the previously-opened issue here: #150

**Comment by vukanac** [comment]
Sorry, I set wrong title.
Point is, I don't want to use SSH, just plain FTP, in simplest possible form.

Plain FTP don't need ssh key
->
PHPloy should not require nor ask about ssh key file!

Am I right?

**Comment by banago** [comment]
Seems you need the server title too on your deploy file, like this:

    [staging]
    quickmode="ftp://username:password@hostname/public_html/directory"

Please check it out and let me know.

**Comment by vukanac** [comment]
Works OK! Thank you!
