### ISSUE TITLE
Plus sign (+) in passwords fail

### ISSUE THREAD

**Issue by hellodaniel** [banago/PHPloy#161]
I've done a bit of testing and the site definitely fails when a plus sign is in the password. I've tested with most other symbols and it seems fine. 

I've just updated to v3.5.1 from 2.something and this definitely wasn't an issue previously. 

I've resolved the problem by changing the password but since auto-generated password sometimes contain + signs it might be work looking into. 

Example output: 

	|----------------[ 0.00B Deployed ]----------------|
	PHP Warning:  ftp_login(): Login authentication failed in phar:///Users/daniel/.bin/	phploy/`vendor/banago/bridge/src/Backend/Ftp.php on line 70
	
	Oh Snap: Could not login to 'hostname.com' as 'username'
	
Failed password example: `kW~Ax3(r}^k+`

**Comment by andresnijder** [comment]
Using quotes will do the trick:
pass = 'kW~Ax3(r}^k+'

**Comment by hellodaniel** [comment]
Doesn't help (have tried double and single quotes).

**Comment by banago** [comment]
@andresnijder and @hellodaniel a fix for this is coming in a minute. Thanks for reporting it.
