### ISSUE TITLE
Purge deletes root assets when path is specified incorrectly

### ISSUE THREAD

**Issue by hellodaniel** [banago/PHPloy#162]
When specifying an incorrect folder the entire root is purged. This seems dangerous as it's very easy to misconfigure and lose required files in a deploy.

e.g.: 

- `purge[] = '/app/folder'` Purges root (even if /app/folder exists)
- `purge[] = '/app/folder/*'` Purges root (even if /app/folder exists)
- `purge[] = '/file.ext'`   Purges root (even if /file.ext exists)
- `purge[] = 'app/folder/'` **Works as expected**

Example output:

	SERVER: staging
	   No files to upload or delete.
	Purging directory /app/tmp/cache/models/
	 - .revision is removed from directory
	 - .travis.yml is removed from directory
	 - .user.ini is removed from directory
	 
(note .revision exists in the root NOT in /app/tmp/cache/models/)

**OS:** Mac OS X

**phploy Version:** 3.5.1

**Comment by iMicknl** [comment]
+1. Just had the same issue today

**Comment by Agnis-LV** [comment]
+1. Just had the same issue today - lost ~8GB of important data this way... ;(
Problem is in the function:
   public function purge($purgeDirs){
        foreach ($purgeDirs as $dir) {
            $origin = $this->connection->pwd();
            $this->connection->cd($dir);
            if (! $tmpFiles = $this->connection->ls()) {}

There is no check that $this->connection->cd($dir); succeeds, when it fails pwd does not change and the files in $origin get purged.

**Comment by banago** [comment]
@hellodaniel, @iMicknl and @Agnis-LV this issue is now fixed. Please check grab latest version of PHPloy (3.5.6).

@Agnis-LV I'm very sorry you lost your 8GB of data. To show my regret I put this put a note about this incident on [PHPloy source code](https://github.com/banago/PHPloy/blob/3.5.6/src/PHPloy.php#L1131). I hope this cheers you up a bit. :smile: 

Happy deploying!
