### ISSUE TITLE
Add support for post deployment script

### ISSUE THREAD

**Issue by StyxOfDynamite** [banago/PHPloy#163]
Would be great if we could give the name of a script to be run after deployment.

Example use-cases.

* database migrations
* tests
* server configuration changes
* restart services
* updating remote dependencies

I'm deploying to several environments in the following order.

dev - private local development instance
test - private remote test server 
qa - limited access server where work can be tested by client  
live - clients current public site

at least for the first 3 I'd be happy to automate post-deployment steps, things like updating composer, restarting nginx or apache, running database migrations, adding .conf block for new features that run on a dedicated subdomain.

I know there are alternatives to PHPloy but for most of the projects I work on the client(s) aren't interested in the financial overheads attached to CI for the development side of things.

If we could add a single or multiple scripts to the repo and have PHPloy trigger them in order it would make things that little bit more awesome.

Apologies if this is something that's already been requested or is in the works, I did a search and couldn't find a related feature request, enhancement or closed ticket.

**Comment by banago** [comment]
@StyxOfDynamite can you please add this post to this issue here: #51 Thanks!

**Comment by StyxOfDynamite** [comment]
done.

**Comment by banago** [comment]
:+1:
