### ISSUE TITLE
Use command line paramter for password

### ISSUE THREAD

**Issue by swiffer** [banago/PHPloy#164]
It would be nice to not store the ftp pass in deploy.ini but use a command line paramter instead, so password is not in repository. GitLab for example allows ci to create secret variables that can be used when running the PHPloy tool.

Is it possible to add this functionality?

**Comment by banago** [comment]
This is offered by PHPloy too. Just remove password from your 'deploy.ini' file and you will be promoted to enter a password. Please let me know how it goes.

**Comment by swiffer** [comment]
is it possible to submit password with command line parameter to ? i don't know how to insert powershell env var when php waits for input
