### ISSUE TITLE
Can't connect to server using dsa key.

### ISSUE THREAD

**Issue by paulEgotribe** [banago/PHPloy#167]
Is it posible to add the $methods to the ssh2_connect(); http://php.net/manual/en/function.ssh2-connect.php

$methods = array('hostkey'=>'ssh-rsa, ssh-dss'); will be good enough for me but i can't add this trough the deploy.ini.

Tnx!

**Comment by banago** [comment]
@victorstanciu I had a good look into using auth keys and seems I cannot make it work. I get this:

    PHP Warning:  ssh2_auth_pubkey_file(): Authentication failed for testuser using public key:
    Callback returned error in phar:///usr/local/bin/deploy/vendor/banago/bridge/src/Backend/Ssh2.php on line 72

Could you please have a look?

**Comment by banago** [comment]
This is now fixed in version 4.0 that landed in master branch a bit ago.
