### ISSUE TITLE
Oh Snap: Could not remove directory

### ISSUE THREAD

**Issue by andresnijder** [banago/PHPloy#168]
Occurs when a directory is not empty.

**Comment by banago** [comment]
@andresnijder this is now fixed. If you could grab the latest version, it would be awesome. Happy deploying!

**Comment by hellodaniel** [comment]
Hi @banago - I don't think this is fixed, just received this (running the latest version) - 
PHP Warning:  ftp_rmdir(): Can't remove directory: Directory not empty in phar:///Users/daniel/.bin/phploy/vendor/banago/bridge/src/Backend/Ftp.php on line 212
