### ISSUE TITLE
Exits when directory has already been removed

### ISSUE THREAD

**Issue by hellodaniel** [banago/PHPloy#169]
If the directory has already been removed (i.e.: no longer exists on remove host, possibly due to a previous commit adding and removing it) then PHPloy exits improperly. This is happening frequently to me and driving me nuts! 

Example: 

	× 39 of 39 app/subdirectory/file.ext
	PHP Warning:  ftp_rmdir(): Can't remove directory: No such file or directory in phar:///Users/daniel/.bin/phploy/vendor/banago/bridge/src/Backend/Ftp.php on line 210

	Oh Snap: Could not remove directory '/Users/daniel/Sites/site/app/subdirectory/'

This is different to #168 (which is when a folder ISN'T empty) but maybe could be merged as the same issue? Just exiting when folders don't remove is probably what needs to be resolved...

**Comment by iMicknl** [comment]
I have the same issue. How do you fix it now? I can only fix it by doing a manually deploy and doing a --sync..

**Comment by hellodaniel** [comment]
@iMicknl I haven't found a fix - I've just been fixing it manually and using DeployBot instead where possible. Never had this issue in [v2](https://github.com/banago/PHPloy/tree/legacy) so I'm going to ditch 3 in favor of this for a while...

**Comment by banago** [comment]
@hellodaniel and @iMicknl sorry for this issue. It is now fixed. If you could grab the latest version, it would be awesome. Happy deploying!
