### ISSUE TITLE
Unable to delete files in submodules

### ISSUE THREAD

**Issue by baldurpan** [banago/PHPloy#171]
I'm doing some testing with submodules and FTP deployment.
I added some dummy files and a dummy submodules called "mysubmodule".
Uploading seemed to work alright, with some PHP warnings though, but then I tried removing a file (somenewfile.txt) from the submodule, commited, pushed, everything looks good.
Deployment time.....

```bash
SUBMODULE: mysubmodule
! 1 of 1 somenewfile.txt not found
```

Oh no. Not found.
Thus the file remains on the server. :/

Screenshot.
 
![screen shot 2015-10-10 at 11 40 48](https://cloud.githubusercontent.com/assets/5663654/10411004/d5197122-6f45-11e5-9d6c-08bb5dc91295.png)

**Comment by banago** [comment]
@baldurpan thanks for reporting this. I was able to reproduce this error and eventually fix it. Grab the latest version of PHPloy and see for yourself :smile: Happy deploying!

**Comment by baldurpan** [comment]
Sweet! Thanks mate. ;)
Quick question. Will there be a submodule supported rollback any time soon?

**Comment by banago** [comment]
@baldurpan that's a tedious tasks and need a bit more of mental space as of what I can give it right now, so I won't be very soon I think. I hope you won't miss it too much.
