### ISSUE TITLE
Initialize deploy.ini

### ISSUE THREAD

**Issue by baoweber** [banago/PHPloy#173]
Thanks for the great app. Would you be up for including something like `phploy --init`, that would create sample deploy.ini file? I cloud try to code it and send a pull request.

**Comment by banago** [comment]
@martinkryl I'd be more then happy to merge your pull request. So get coding :smile:

**Comment by martinkryl** [comment]
Sorry for the delay, I will try to code it over the next week, I was just checking whether it would be something that you would approve of.

**Comment by baoweber** [comment]
Thanks for the merge, I am closing this issue :+1:
