### ISSUE TITLE
Requirements PHP 5.4

### ISSUE THREAD

**Issue by Agnis-LV** [banago/PHPloy#174]
At requirements there is written that PHP 5.3+ command line interpreter (CLI) is needed.
But in PHPloy.php file in atleast 2 places there is a construction $array = []; (search for string "[]") which is a PHP 5.4+ feature.
Also function array dereferencing is a PHP 5.4+ feature, e.g. foo()[0].

**Comment by Agnis-LV** [comment]
Also there are some requirements for GIT version.
Git version <= 1.7.12.4 will not work because there is no `git -C` command line option. It will return Unknown option: -C.

**Comment by banago** [comment]
@Agnis-LV thanks for pointing these out.
