### ISSUE TITLE
Cannot create directory with hidden file

### ISSUE THREAD

**Issue by indrisepos** [banago/PHPloy#176]
* My system: ubuntu 12.04 + proftpd default config
* The fail: At first deploy, when the .revision file not exist, the PHPloy upload all files and direcories to the ftp server. If I deploy a directory with hidden file then can not make that directory. 
* In deep: 

1) In the Banago\Bridge\Backend\FTP->mkdir() does not check the direcory exists.
2) The proftpd default config's ListOptions: '-l', it wont list the hidden files.

* A solution: 
```
	public function exists($path) {
// expilicit list all hidden files too
        $listing = @ftp_nlist($this->conn, '-al '.$path);
        if(empty($listing))
            return false;
        else
            return true;
    }


	public function mkdir($dirName) {
// check direcory exist before make direcory
		if(!$this->exists($dirName)){
		    if(!@ftp_mkdir($this->conn, $dirName)) {
				throw new \Exception("Could not create directory '$dirName'");
		    }
		}
		return true;
	}
```

**Comment by banago** [comment]
@indrisepos can you please check PHPloy 4.0.
