### ISSUE TITLE
Option to set file permissions

### ISSUE THREAD

**Issue by strauss69400** [banago/PHPloy#177]
hi,

i have a little problem about right on my files.

when i upload my files by fillezilla, rights are good.Indeed, my files are in 664 and my folders in 775.
but the problem when i upload my files by phploy, rights become 644 and 755 for folder.

why phploy alter right by defaut of the files and folders.

is there a solution to resolve this problem.
i thank you for you help.

PS: sorry for my english

**Comment by JayBizzle** [comment]
`755` should suffice for most server setups. You would only need `775` if apache (assuming your using apache) is run as a different user to the one who owns the folder, but is a member of the same user group, then `775` will suffice.

There is no way for PHPloy to set file/folder permission currently, out of scope in my opinion.

**Comment by banago** [comment]
@strauss69400 this normally happens because of misconfiguration of server users permissions. Even though permission can be enforced by PHPloy, I don't see this being implemented in the foreseeable future. So, I'll have to close this for now, sorry.

**Comment by allysonsouza** [comment]
Hi @banago,

I make websites using WordPress, and I'm having problems with file permissions too. 

How I see, you are also a WordPress user too, these problems of file permissions happens because of misconfiguration of my host? I'm using a shared host, and 755 for wp-content doesn't work, i fixed to 775 in CPanel and then everything works perfeclty.

**Comment by gajanak** [comment]
Would be nice to set not only fixed, but also use the permission of the orginal file.
(git tracks permissions).

Additionaly, it would be nice, to set date/time, too.
( MDTM,MFMT ... )
Perhaps take date of last change in repository

**Comment by banago** [comment]
@strauss69400, @allysonsouza, @JayBizzle and @gajanak there has been an implementation of this by @fsalomon on this pull request: https://github.com/banago/PHPloy/pull/248. Everything is merged and ready to try out. Please grab latest version and report any issues. Thanks!

**Comment by allysonsouza** [comment]
Thanks @banago! I'll try as soon as possible!

**Comment by banago** [comment]
@fsalomon this feature introduced some issues. The files were either `private=0700` or `public=774`. This was not a desired outcome, so I had to deactivate visibility setting by default for now. If you can, please look into this again.

**Comment by fsalomon** [comment]
Yes, but (S)FtpAdapter doesn't have it. Anyways, I just made the visibility unset by default, so people can still rely on grandfathered behavior. See https://github.com/banago/PHPloy/pull/256 One can now set one of
+ visibility = public
+ visibility = private
+ permissions = 0xxx 

or one can use the low level permPrivate, permPublic. Even though I'm not sure of the use case.

**Comment by Rafeethu** [comment]
I'm also facing the permission issue using sftp. For new file the permission is set to 664 where as i want that to be 755.

i have set the following in my phploy.ini file
visibility = public
permissions = 0755
permPublic = 0755

any update on this. my phploy version is 4.3.5.

**Comment by jjeaton** [comment]
Just ran into this. Any new folders I create end up with 750 permissions, and the site breaks.

Seems to be exactly what was happening here: https://github.com/banago/PHPloy/pull/248#issuecomment-221707305

For me, deploying via SFTP is only necessary for shared/managed hosting environments where SSH isn't available, so server misconfiguration isn't necessarily something that can be controlled. Any idea what that misconfiguration would be?

Also, is this an issue with PHPloy or Flysystem?

**Comment by jjeaton** [comment]
I was able to fix my issue in #283 by adding support for `directoryPerm` in the flysystem SFTP adapter. https://github.com/thephpleague/flysystem-sftp/blob/master/src/SftpAdapter.php#L54
