### ISSUE TITLE
Creating a directory on my server

### ISSUE THREAD

**Issue by dling61** [banago/PHPloy#178]
I have a directory structure on my git repository /public/javascripts, /public/stylesheets and so on. I want to deploy everything under /public directory to my hosting server under /test directory. But i don't want "public" directory being created on my server. How can i do that? Does Phploy support it?

**Comment by banago** [comment]
PHPloy mirrors the structure of your git repository. So on your server will be created the same directory structure as locally. Hope it make sense.
