### ISSUE TITLE
"phploy -o" do not upload untracked submodules correctly

### ISSUE THREAD

**Issue by louislam** [banago/PHPloy#180]
Some composer packages of my project are using "dev-master" version. Those packages in "vendor" contain ".git" directory. It seems that the git command do not list out the untracked submodule in this case. 

![2015-11-07_224211](https://cloud.githubusercontent.com/assets/1336778/11015693/8a9ec99e-85a2-11e5-8618-f6951ed20ae0.png)

As my "vendor" folder is ignored by git, adding arg "--submodules" is not working too.

![2015-11-07_224553](https://cloud.githubusercontent.com/assets/1336778/11015695/9c81df16-85a2-11e5-9165-ca1e25ff81e8.png)

**Comment by banago** [comment]
@louislam, the  `-o` flag has now been replaced. Please check out latest version of PHPloy.
