### ISSUE TITLE
No help output

### ISSUE THREAD

**Issue by baoweber** [banago/PHPloy#183]
I have been trying to issue a fix for the `--help` command as it point to a non-existent readme.md file (in the src folder), but then I realized that the project readme isn't packed into phar file anyway.  Sould I try to create a brief help that would sit in the src folder and thus would show when the user asks for help?

**Comment by malukenho** [comment]
+1

**Comment by banago** [comment]
@baoweber we will move away from the file solution and have the help be build on the fly by using something like this hopefully: https://github.com/nategood/commando Thanks for reporting this.

**Comment by JayBizzle** [comment]
A switch to [Symfony/Console](https://github.com/symfony/Console) would be nice

**Comment by banago** [comment]
@baoweber and everyone, PHPloy 4.0 now has a nice help output. Check out out:

    phploy --help
