### ISSUE TITLE
skip[] isn't skipping folder

### ISSUE THREAD

**Issue by rasmuswoelk** [banago/PHPloy#184]
Hi

I'm using the latest version of PHPloy (great stuff!). When I try to skip my "production"-folder in my theme folder it doesn't recognize the setting for some reason. It uploades my entire production folder with node_modules and all.

Lines in my deploy.ini:
path = /exerp
skip[] = '/exerp/wp-content/themes/exerp/production/node_modules/'
skip[] = '/exerp/wp-content/uploads/*' 

I use the FTP scheme and it uploads files just fine.

What am I doing wrong here?

**Comment by rasmuswoelk** [comment]
My gitignore wasn'nt functioning properly so that fixed my issue.

**Comment by banago** [comment]
:+1:
