### ISSUE TITLE
Example for public and private key.

### ISSUE THREAD

**Issue by craftpip** [banago/PHPloy#188]
I get the error `Authentication failed for ubuntu using public key: Invalid public key data`.
My public key file looks like so: 
```
AAAAB3NzaC1/.....
```

Can someone please correct me on this ?
Thanks

**Comment by banago** [comment]
Please remove public file from display.

**Comment by banago** [comment]
We have to open tickets for this now. I could not get this to work on my end and waiting for the contributor of this feature to get back before I do something about it. I'm closing this. Please watch the other tickets for now.
