### ISSUE TITLE
Phploy V3.5.6 is not working with Git V1.8.3 on Window-7(64 bit)

### ISSUE THREAD

**Issue by sandeepsrivastava** [banago/PHPloy#191]
Hi team,
I am working on widow 7 and PHPloy was working fine until I updated the version with 3.5.6. After updating the version of PHPloy (3.5.6) it started showing error  "Unknown option: -C".

Although my GIT version is 1.8.3 which fulfil your minimum requirement but still  it seems related to GIT version. I updated the git version (2.6.3) and Issue got resolved.

I also reviewed the code and found the issue (-C should be -c ) on line No. 672 under the PHPloy/src/PHPloy.php file for git version 1.8.3. But it will not work on latest GIT version.

I think you should update the minimum requirement of GIT.

**Comment by banago** [comment]
Thanks for reporting this. :+1:
