### ISSUE TITLE
Could not change directory to ""

### ISSUE THREAD

**Issue by chlab** [banago/PHPloy#192]
Hi

Just tried using phploy. This is whay my deploy.ini looks like:

```
[staging]
    scheme = sftp
    user = developer
    pass = ***
    host = host02
    path = "/deploy.test"
    port = 22

    include[] = "htdocs/"
```

When I run `phploy -s staging` I get
````
PHP Notice:  Undefined variable: data in phar:///usr/local/bin/phploy.phar/vendor/banago/bridge/src/Backend/Ssh2.php on line 89

Notice: Undefined variable: data in phar:///usr/local/bin/phploy.phar/vendor/banago/bridge/src/Backend/Ssh2.php on line 89

Oh Snap: Could not change directory to ''. Please make sure the directory exists.
```

Any help on what's wrong here?
If I connect to my SFTP via the same credentials in an FTP program it works and as far as I can tell, the folder exists.

**Comment by chlab** [comment]
Found out what's wrong. I had to supply the full path on the server `/var/www/vhosts/deploy.test`.

Still, looks like the error isn't working properly. Also: a verbose mode would be nice!

Thanks for the good work!

**Comment by banago** [comment]
The dot (.) in the directory name might be the culprit.  Also, the verbose mode is available by running `--debug`.  

Thanks for using PHPloy.

**Comment by chlab** [comment]
Ok thanks. Don't think so, it worked with the full path. I think the error message is just using the wrong variable.

**Comment by Ziggizag** [comment]
It should read:

`throw new \Exception("Could not change directory to '{$parsedUrl['path']}'. Please make sure the directory exists.");   `

rather than:

`throw new \Exception("Could not change directory to '{$data['path']}'. Please make sure the directory exists."); `
