### ISSUE TITLE
Mapping directories?

### ISSUE THREAD

**Issue by chlab** [banago/PHPloy#195]
I want to upload the contents of the `www/` directory to the root `/` of the ftp server. Is this possible with PHPloy?

I would be open to implementing this if it's not possible as I think it's a common usecase for people to have their deployable code in a `www/` oder `build/` folder. As I see it, there are two ways to implement this:

1. add a `base_path/` (or similar) directive to each server-block of the deploy.ini. This would pose the question how it relates to the `include/` and `exclude/` directives.
2. add a general mapping syntax that allows you to map local folders to server folders.

I think 1 is simpler and more straightforward. Any thoughts from an author?

**Comment by banago** [comment]
This is not a hard technical problem, but I don't have the time to implement it right now. Do you think you can help here? I'd be more then happy to merge your contributions.

**Comment by chlab** [comment]
I started playing around with this on the weekend. I'll send a pull request when I'm finished. Might take a while though, kinda busy at the moment. I'll close this issue for the time being.

**Comment by lalop** [comment]
Hello,
is there any news ?

**Comment by banago** [comment]
Yes, look into the `copy` setting.

**Comment by lalop** [comment]
you mean if I want to push my `public/`  folder into the remote `www/` I have to push `./` to `./` then copy `public` into `www` ?

**Comment by lalop** [comment]
or this will just take the content of public and put it inot www ?

**Comment by banago** [comment]
This is all we can have at this moment:

    ; Directories that should be copied after deploy, from->to
    copy[] = 'public->www'

**Comment by lalop** [comment]
ok thank you

**Comment by chlab** [comment]
Cool that this happend. I was working on it but then changed employers and no longer had need for it and kind of forget about it :) sorry.

**Comment by banago** [comment]
@chlab all good. Are you using PHPloy at new job?

**Comment by chlab** [comment]
Nope, doing Django now and using Fortrabbit for personal PHP projects.
