### ISSUE TITLE
Cannot remove 

### ISSUE THREAD

**Issue by dendeffe** [banago/PHPloy#196]
I was getting this error a lot (also in the latest version)

Oh Snap: Could not remove directory 'wp-content/plugins/wordpress-seo/vendor/yoast/license-manager/tests'

Not sure if it’s always that specific folder.
Going back to Version 2 of PHPloy works.

**Comment by banago** [comment]
This issue is fixed in verison 4.0. Do you think you can grab it and give it a try: https://github.com/banago/PHPloy/tree/4.0

Thanks.

**Comment by dendeffe** [comment]
Hmm reinstalled 3.5.6 which does indeed seem to fix this.
Weird. I thought I already had that version.
