### ISSUE TITLE
Remote status

### ISSUE THREAD

**Issue by ogrosko** [banago/PHPloy#199]
What about deploy command option --status which give you actual remote revision ID
Is it possible to implement?

**Comment by banago** [comment]
Yes, that would be very easy to implement. In what case do you think one might need this?

**Comment by ogrosko** [comment]
I need sometimes to check which version is deployed on remote server and compare with git log etc.
If it should be implemented for me, so let it be ...

**Comment by banago** [comment]
Do you know you could do `phploy --list` to see what files are up for upload? Would this be good enough?

**Comment by ogrosko** [comment]
Yes of course ;) But sometimes there are too many files changed so I want to check it in git log.

**Comment by banago** [comment]
Alright then, if you want it, you have to implement it. :smile:
