### ISSUE TITLE
Choose which branch deploy

### ISSUE THREAD

**Issue by davidromani** [banago/PHPloy#20]
It would be interesting if we can set on deploy.ini which branch use to deploy. I use capifony to deploy my Symfony projects and it has this helpful feature.

Thx.

**Comment by banago** [comment]
Because there is not a great demand for this feature, and you can actually achieve the same results in different way, I am retiring this proposal. Thanks for you input guys.

**Comment by banago** [comment]
This is being implemented in 4.0 branch.

**Comment by davidromani** [comment]
:+1:

**Comment by banago** [comment]
@davidromani and @SimonEast, deploying from a branch is not implemented.

Big thanks to @InfinityWebMe for this.
