### ISSUE TITLE
SSH2 pecl extension installation on osx 10.11

### ISSUE THREAD

**Issue by adrianocr** [banago/PHPloy#200]
So phploy works fine through ftp but I would love if I could use it through sftp. However on osx el capitan (10.11.3) I can't get the pecl extension to install. Anyone else have an issue with this? 

The error is: `Oh Snap: ssh2 PECL extension is not installed. Please install it to use ssh.`

**Comment by dendeffe** [comment]
@adrianocr Just got it working (with Mamp (PRO, an old version)) on el capitan.

These guides helped (you have to modify the instructions a bit, though):

https://www.allsupported.com/install-ssh2-on-osx-mamp-pro/
http://www.dionysopoulos.me/add-the-ssh2-extension-to-mamp.html

**Comment by adrianocr** [comment]
@dendeffe I just got it working. I used Homebrew to install PHP56 with the --with-perl flag. That built and added php56 to my /usr/local/bin directory and then I set that as my default php. I then used PECL to install ssh2 and it's all working now. 

The issue seemed to be that PECL couldn't install extensions to the default php. I'm assuming that's because it's based out of /usr/bin/ and the new El Capitan policies don't really allow for modifying the system at that level? I'm not sure. But anyway I got it working. 

Step 1: `brew install php56 --with-perl`
Step 2: add the new php to your path/zshrc/bashrc
Step 3: In your terminal `source ~/.bashrc`
Step 4: `pecl install ssh2`
Step 4: `phploy`

**Comment by banago** [comment]
Guys, it's high time you jumped into 4.0 version. :smile_cat:

**Comment by adrianocr** [comment]
@banago does 4.0 not require the ssh2 extension or something? Haha

**Comment by banago** [comment]
Nope. It uses libssh library. :smile:
