### ISSUE TITLE
SSH2 installed, can not upload to SFTP

### ISSUE THREAD

**Issue by dendeffe** [banago/PHPloy#201]
As far as I can see, I have SSH2 installed:
http://take.ms/Jbxh5
(On Mamp Pro 2.2, via https://www.allsupported.com/install-ssh2-on-osx-mamp-pro/)

File also seems to be on the location I expect it to be: http://take.ms/6lDjk

But PHPLOY still gives the error Oh Snap: ssh2 PECL extension is not installed. Please install it to use ssh.

Any idea what else I can do?

**Comment by dendeffe** [comment]
Never mind. I got there eventually. Still had to add the extension properly to php.ini.

This helped: http://www.dionysopoulos.me/add-the-ssh2-extension-to-mamp.html

**Comment by banago** [comment]
:+1: Please make sure to check out 4.0 branch that does not require ssh2 extension any longer. Thanks for using PHPloy.
