### ISSUE TITLE
Proposal - Bind a server to a branch

### ISSUE THREAD

**Issue by InfinityWebMe** [banago/PHPloy#202]
Hello,

It would be nice to be able to bind a server to a branch. 

Example : [production] bind to master branch and [staging] bind to develop branch.

Thoughts?

**Comment by banago** [comment]
This has been proposed before and I like the idea. If you would like to develop this, I'd be happy to merge.

**Comment by InfinityWebMe** [comment]
It's done, i close this issue :)

https://github.com/banago/PHPloy/pull/206
