### ISSUE TITLE
Upload then delete

### ISSUE THREAD

**Issue by hellodaniel** [banago/PHPloy#203]
I've been using both PHPloy 2 and PHPloy 3 simultaneously for a while now and I've noticed one significant difference that I'd like to ask about: 

- PHPloy 2.x seems to upload all new/modified files THEN delete
- PHPloy 3.x seems to delete all files THEN upload new/modified ones

I much prefer the way PHPloy 2 does it - especially when moving files because they simultaneously exist in the 2 locations while updating. I've almost exclusively gone back to using v2 simply because there is less chance of things breaking on the site (due to push THEN delete) but PHPloy 3 goes in and deletes everything first (and if it happens to fail leaves a broken mess).

Is this a conscious decision with a reason behind it? Any chance to swap it back to PHPloy 2.x style, which seems considerably more reliable?

**Comment by banago** [comment]
I'm sure I had an reason for this change, but I'm not sure now. Keeping this around to check for version 4.0.

**Comment by banago** [comment]
@hellodaniel this is now addressed. Thanks for using PHPloy.
