### ISSUE TITLE
4.0 - Revision not retrived on some hosts

### ISSUE THREAD

**Issue by InfinityWebMe** [banago/PHPloy#204]
Hello,

i try to use phploy 4 but when i launch a sync, every time, i had the message "No revision found - uploading everything..".

On debug mode, i had "Fetching .revision file" and when i display the list of files with "print_r($this->connection->listContents(), true)", the file is there.

```
Array
(
    [0] => Array
        (
            [type] => file
            [path] => .revision
            [visibility] => public
            [size] => 40
            [dirname] =>
            [basename] => .revision
            [extension] => revision
            [filename] =>
        )

    [1] => Array
        (
            [type] => file
            [path] => index.php
            [visibility] => public
            [size] => 56
            [dirname] =>
            [basename] => index.php
            [extension] => php
            [filename] => index
        )

    [2] => Array
        (
            [type] => file
            [path] => test.php
            [visibility] => public
            [size] => 194
            [dirname] =>
            [basename] => test.php
            [extension] => php
            [filename] => test
        )

)

```

i'm with FTP connexion and ,with version 3, no issue.

Any idea ?

**Comment by banago** [comment]
I've run into this myself. I'll address this as soon as I find a bit of
time.

Thanks for reporting it.

**Comment by banago** [comment]
@InfinityWebMe you have the honor to close this issue. :+1:

**Comment by InfinityWebMe** [comment]
@banago I still have the issue :-/

**Comment by banago** [comment]
Sorry, I though this was fixed. It's OK, I'll look into that.

**Comment by InfinityWebMe** [comment]
I reported the issue in FlySystem repostiory : https://github.com/thephpleague/flysystem/issues/601

**Comment by InfinityWebMe** [comment]
Issue resolves with this : https://github.com/thephpleague/flysystem/pull/605

But actualy only on dev-master.

**Comment by banago** [comment]
Great. By the time we go stable with 4.0 the will have tagged it hopefully.
Thanks for sticking to this.

**Comment by banago** [comment]
@InfinityWebMe this should now be fixed. Please check out latest version.
