### ISSUE TITLE
composer.json requirements are all @dev

### ISSUE THREAD

**Issue by deltamualpha** [banago/PHPloy#207]
This makes it harder to install PHPloy using composer, because composer by default refuses to install dev versions of required packages unless they're specifically whitelisted in the root composer.json *or* the root changes its minimum required-stability. See [the composer documentation](https://getcomposer.org/doc/04-schema.md#minimum-stability) for more details, and composer issue reports like <https://github.com/composer/composer/issues/1478> for examples of how this works in practice.

**Comment by banago** [comment]
@deltamualpha please grab 4.0 version where this issue is addressed: https://github.com/banago/PHPloy/tree/4.0
