### ISSUE TITLE
FTP 'passive' option

### ISSUE THREAD

**Issue by Eartz** [banago/PHPloy#208]
Hi,

First thank you for this project, It's awesome !  

I noticed that in the current master, if the scheme is ftp it isn't possible to disable the passive mode even with the `passive = false` flag in deploy.ini.

To allow this I need to change things a bit in src/PHPloy.php itself and in a dependency (Banago\Bridge\Backend\FTP).

My question : by looking at the code, it seems that this problem is fixed in the 4.0 branch but I'm not sure (I haven't tried it), so is it worth creating a PR for or not ?

cheers :-)

**Comment by banago** [comment]
Hey @Eartz 

Please jump into 4.0 branch because I'm not actively maintaining 3.x any more. Thanks.
