### ISSUE TITLE
Remote repo

### ISSUE THREAD

**Issue by ankit-krishinc** [banago/PHPloy#209]
Hello,

Thanks for this great tool to deploy.

It seems it is tracking local git repo. Is it possible to track revision on remote and deploy the changes from remote repo to server?

This is required because the person who is deploying may not have clone of central repo.

**Comment by banago** [comment]
@ankit-krishinc this is not possible at this point. Because remote repos are `bare` repos (don't have a worktree) and PHPloy needs a worktree to work with. This is something I might add in the future because is a nice thing to have. Stay tuned.
