### ISSUE TITLE
Installing PHPloy globally in Windows

### ISSUE THREAD

**Issue by banago** [banago/PHPloy#214]
Here is how you install PHPloy globally on Windows:

1. Extract or clone the PHPloy files into a folder of your choice
2. Ensure phploy.bat can find the path to php.exe by either:
    * Adding the path to php.exe to your system path
    * Manually adding the path inside phploy.bat
3. Add the phploy folder to your system path
4. Run `phploy` from the command prompt (from your repository folder)

Adding folders to your *system path* means that you can execute an application from any folder, and not have to specify the full path to it.  To add folders to your system path:

1. Press WINDOWS + PAUSE to open Control Panel > System screen
2. Click "Advanced System Settings"
3. Click "Environment Variables"
4. Under "System variables" there should be a variable called "Path".  Select this and click "Edit".
5. Keep the existing paths there, add a semi-colon `;` at the end and then type the location of the appropriate folder.  Spaces are OK, and no quotes are required.
6. Click OK

**Comment by lisurc** [comment]
Could it  be possible to move this "doc issue" to the Wiki? Even it's mentioned in the readme file, browsing to "Closed Issues" to find it feels quite misleading :)

**Comment by Humni** [comment]
Done... https://github.com/banago/PHPloy/wiki/Installing-PHPloy-globally-in-Windows

**Comment by Humni** [comment]
Never mind, @banago deleted the wiki.

**Comment by Humni** [comment]
@banago The idea of most wikis is that they grow over time, becoming more detailed and accurate as community members contribute missing information/remove incorrect information.
