### ISSUE TITLE
4.0.0-Beta - Connection protocol

### ISSUE THREAD

**Issue by ankit-krishinc** [banago/PHPloy#217]
Hello,
Thanks for the amendments found in the 4.0.0-Beta version especially the 'branch' directive.

However, it looks like it supports FTP and sFTP only. Connection through SSH is seemingly not working now.

--
Thanks

**Comment by banago** [comment]
Since PHPloy 4 makes use of the flysystem package, it does not support ssh. I'm pretty happy with just SFTP for now. Any reason why you would want SSH support?
