### ISSUE TITLE
Help spread the word about PHPloy

### ISSUE THREAD

**Issue by banago** [banago/PHPloy#218]
It has been a great ride developing PHPloy, and it's a great feeling to finally ship version [4.0 stable](https://github.com/banago/PHPloy) to the world. This would not be possible without your help and feedback guys, so thank you.

I spend considerable time and effort developing and maintaining PHPloy. At his point, I'd be comfortable to ask for donations, if I needed to, and I'm sure I'd receive some love in the form of :moneybag:. But, thankfully, I don't need donations.

However, what I'd love to see happen instead is PHPloy gaining a bit more adoption. I cannot complain, it has been great so far, but I'm sure there is a lot of unclaimed territory out there for PHPloy. 

Thus, my request to each and everyone of you is, please **tweet**, **facebook** and/or **blog** about PHPloy. If you have found PHPloy helpful, please help it back to become a bit more popular. 

Thank you,
Baki
:love_letter:

**Comment by collizo4sky** [comment]
You've done a great job. Will sure help spread the word about it awesomeness.
