### ISSUE TITLE
Can not find files but they are there

### ISSUE THREAD

**Issue by reibejoy** [banago/PHPloy#220]
I am having a weird problem. Probably config related. I get the following messages: 

`jmueller@Jans-iMac:~/Desktop/repos/phploytest$  php phploy -s staging -l`
> ---------------------------------------------------
|                   PHPloy v4.0                   |
---------------------------------------------------
LIST mode: No remote files will be modified.
No revision found - uploading everything...
Already on 'master'
> 
> SERVER: staging
   Files that will be uploaded in next deployment:
      bar
      foo

`jmueller@Jans-iMac:~/Desktop/repos/phploytest$ php phploy -s staging`

> ---------------------------------------------------
|                   PHPloy v4.0                   |
---------------------------------------------------
No revision found - uploading everything...
Already on 'master'
> 
> SERVER: staging
 ! File not found - please check path: /Users/jmueller/Desktop/repos/phploytest/bar
 ! File not found - please check path: /Users/jmueller/Desktop/repos/phploytest/foo
> 
> |----------------[ 0.00B Deployed ]----------------|

The path I have configured is: 
> path = /httpdocs/phploytest/

It is definitely there and writable. I can confirm this, as phploy uploads its `.revision` file to that location. 

After I run `php phploy -s staging` once more I get the above error message. When I run again (no local changes made), I get this message: 

> ---------------------------------------------------
|                   PHPloy v4.0                   |
---------------------------------------------------
> Already on 'master'
> 
> SERVER: staging
> 
>  No files to upload or delete.
> 
> |----------------[ 0.00B Deployed ]----------------|

**Comment by banago** [comment]
The error says the files does not exist locally. I'm finding it hard to figure out what your issue is exactly.

**Comment by dl1ely** [comment]
Well, it is easy to spot. i guess foo and bar were created by „touch“ and are 0 byte long. PHPloy thinks they are not there because the return value check when reading the files is done too sloppy. The fix is in #222.

**Comment by reibejoy** [comment]
> Well, it is easy to spot. i guess foo and bar were created by „touch“ and are 0 byte long. PHPloy thinks they are not there because the return value check when reading the files is done too sloppy. The fix is in #222. 

That's exactly what happened. Thanks for pointing it out and fixing it.

**Comment by banago** [comment]
@reibejoy this is now merged in master. Thanks very much for reporting it. And @dl1ely thanks very much for figuring it out.
