### ISSUE TITLE
Posibility upload specific folder from repository

### ISSUE THREAD

**Issue by MichalSeidler** [banago/PHPloy#224]
Hello, i have more folders in my project e.g. folder A and B i need upload CONTENT of folder A (not folder but only content) into dir A on server and content of B into B on server (or another server). 

Easiest solution can be add support of phploy.ini in subdirectories. When i try it now it writes me that is no git repo in subdirectory.

**Comment by banago** [comment]
@MichalSeidler grab lastest update to PHPloy and try this command:

    ; Directories that should be copied after deploy, from->to
    copy[] = 'public->www'

Is this what you are asking for?
