### ISSUE TITLE
Unsupported git-diff status: f

### ISSUE THREAD

**Issue by dendeffe** [banago/PHPloy#225]
I’m getting

Oh Snap: Unsupported git-diff status: f
Trying to do phploy.phar -l

Using phploy 4.0

Most sites work properly, not this one though.
Haven’t been able to find out what git diff-status f is, so no idea where to start looking for that either.

**Comment by banago** [comment]
As a temporary solution, reset your `.revision` file, either delete it or `phploy --sync="hash-here"`. I'll look into this.

**Comment by banago** [comment]
Basically your `.revision` file is out of sync. I improved the error message so it's more clear.

**Comment by dendeffe** [comment]
Ok thanks

**Comment by rajnisheu** [comment]
@banago this does not look to be a revisions issue rather the command being used. Btw, `phploy --sync` does not work and returns tons of errors about ftp and so on.

I was trying to solve the exact issue and it looks the command does not take into account the ini server setting. `phploy --sync="hash-here"` does not expect a server to be defined? I tried providing it in various ways and none worked.

**Comment by banago** [comment]
@rajnisheu what's your php version?

**Comment by rajnisheu** [comment]
5.5.24 xampp
