### ISSUE TITLE
4.1 and 4.1.1 has unmet dependancy

### ISSUE THREAD

**Issue by ChrisWiegman** [banago/PHPloy#226]
The switch to dev-master for league/climate doesn't work as the branch doesn't exist. Here's what packagist says:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - banago/phploy 4.1.1 requires league/climate dev-master -> no matching package found.
    - banago/phploy 4.1.0 requires league/climate dev-master -> no matching package found.
    - Installation request for banago/phploy ^4.1 -> satisfiable by banago/phploy[4.1.0, 4.1.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by banago** [comment]
@ChrisWiegman yeah, it's because I changed dependency of [CLImate](https://github.com/thephpleague/climate) to 'dev-master' to grab latest fix for an issue. Now seems we are stuck here until he tags the fix. I've notified the dev. 

Do you think you can grab the `.phar` file in the meanwhile?

**Comment by banago** [comment]
@ChrisWiegman dependencies are now updated and good to go. Thanks for reporting this.
