### ISSUE TITLE
Deploy to a "versions" folder.

### ISSUE THREAD

**Issue by Schnoop** [banago/PHPloy#228]
Our projects are big, and a deployment last up to 5 minutes. Depending on what has been changed the live server is broken until the deployment is finished.
I though about creating a "versions" folder, so  that a deployment can run in the background without harming the live code:

```
 lrwxrwxrwx 1 users   20 Apr  6 10:37 public -> version160406/public
 drwx------ 9 users 4096 Apr  1 13:30 version160331
 drwx------ 9 users 4096 Apr  1 13:29 version160401
 drwx------ 2 users 4096 Apr  4 16:05 version160404
 drwx------ 9 users 4096 Apr  6 10:38 version160406
```

The `public` folder is our live webroot where the application is served from. We symlink the live-version to a release. This give us the possibily to rollback to a previous version very easily.

Sure, i can change the deploy directory in the phploy.ini file every morning, but that is error prone - if i omit it one day, i will destroy my current release code.

I suggest an option to tell phploy that i want a new folder every day. phploy creates that folder if is it missing.

```
[staging]
    scheme = sftp
    user = example
    ; When connecting via SFTP, you can opt for password-based authentication:
    pass = password
    ; Or private key-based authentication:
    privkey = 'path/to/or/contents/of/privatekey'
    ; If the private key is encrypted, you must also provide the passphrase:
    keypass = passphrase
    host = staging-example.com
    ; When enabled a new folder on daily base will be created in your deployment path
    ; e.G. /path/to/installation/version_2016_04_04
    version = On
    path = /path/to/installation
```

This will make the deployment more flexible and fail safe.

What do you think?

**Comment by banago** [comment]
@Schnoop I see your point. It's a great feature in itself.

I created PHPloy as a simple deploy tool and I'd love to keep it as simple as possible. It has grown quite big already and this feature would take it out of the simple tools for sure. So, at least for now, I'd suggest you look into other different tools that offer that functionality, like [deployer](https://github.com/deployphp/deployer). I hope you understand. 

I'm open to discussing a simpler solution to this problem, and to do so, let's continue the discussion over at #223. Thanks you.

**Comment by Schnoop** [comment]
There is one big difference between your tool and the mentioned Deployer. To use Deployer, you have to use a ssh connection, which in our case, is not allowed. Yes, we are able to connect as unpriveleged, but uploads are not possible. So we have to stick to the FTP protocoll. 
I don't what your Script to create the symlink, just so have the possibilty, to create a Deploy target/folder depending on the current date.
