### ISSUE TITLE
Problem uploading files with special chars

### ISSUE THREAD

**Issue by Stony2k** [banago/PHPloy#23]
I have found a bug in the script. I'have tried to upload a file in my test environment.

Failed to upload "...../02 Vollmacht (f\303\274r Dritte).pdf". Retrying (attempt 2/10)...
PHP Warning:  ftp_put("......../02 Vollmacht (f\303\274r Dritte).pdf"): failed to open stream: No such file or directory in /usr/local/bin/phploy on line 698

So there are special chars like **ä** or **ü** and so in the name of the files. In this cases its not working.

After running the script i have two folders in the ftp folder.

**"web** and **web** without the quote.

**Comment by banago** [comment]
@Stony2k this issue is now fixed. Thanks very much @maliayas for the input. Happy deployment!

**Comment by Stony2k** [comment]
No problem :+1:  its a great script.

**Comment by banago** [comment]
Hey @Stony2k, make sure to tell the world too on twitter or somewhere. :)

**Comment by Stony2k** [comment]
Ich have no Twitter account but i have shared it on Google+ :)
