### ISSUE TITLE
Listing and uploading files in purge[]

### ISSUE THREAD

**Issue by MichalSeidler** [banago/PHPloy#230]
Is possible to remove purged files from -l and don't upload them when is folder in purge[]?

I have project on localhost. When i test it i create some temp files and cache. I have this directories in purge[]. When i use phploy -l i see that files in purge will be uploaded, when i call phploy all files in purge are uploaded and then removed.

**Comment by banago** [comment]
Interesting scenario. I'll look into it.

**Comment by MichalSeidler** [comment]
On more info: its in include and then in purge because i need include untracked directories and after that purge some files from them

**Comment by banago** [comment]
@MichalSeidler why don't you include just the inner directories in this case? Because this seems a counterintuitive usage of `include[]`. Please let me know if there is a solid reason after this.
