### ISSUE TITLE
cleartext sessions and weak ciphers are not accepted 

### ISSUE THREAD

**Issue by shahidbasheer** [banago/PHPloy#232]
Hi im getting this error connecting ftp. pls help

Warning: ftp_systype(): Sorry, cleartext sessions and weak ciphers are not accepted on this server. in phar://C:/Users/Dell/phploy/bin/phploy/vendor/league/flysystem/src/Adapter/Ftp.php on line 446

**Comment by shahidbasheer** [comment]
Filezila connect with same credential over TLS connection.

**Comment by banago** [comment]
@shahidbasheer please try to use `ftps` connection.

**Comment by shahidbasheer** [comment]
Hi bango
Thanks for your reply i already tried ftps in php.ini setting but it give below error. 

Oh Snap: Please provide a known connection protocol such as 'ftp' or 'sftp'.

**Comment by banago** [comment]
@shahidbasheer can you grab latest master version and try `https` again. It should now work. Let me know.
