### ISSUE TITLE
Submodules

### ISSUE THREAD

**Issue by baldurpan** [banago/PHPloy#233]
Not sure what's going on here, but there is some mixup.
Seems like it's trying to update my submodule with the files from the master repository.
Thus, my submodules never gets uploaded.

---------------------------------------------------
|                   PHPloy v4.1                   |
---------------------------------------------------
Scanning repository...
   Found 1 submodules.
   Found submodule core.
      Scanning for sub-submodules...
Already on 'master'

SERVER: production
Execute : curl -X POST http://demo/hook/deploy/pre
 ^  1 of 8 apps/nota/assets/css/theme.min.css
 ^  2 of 8 apps/nota/assets/js/nt.js
 ^  3 of 8 apps/nota/controller.class.php
 ^  4 of 8 apps/nota/javascript/nt.invoice.js
 ^  5 of 8 apps/nota/plugin/invoice/model/invoice.class.php
 ^  6 of 8 apps/nota/plugin/invoice/section.class.php
 ^  7 of 8 apps/nota/plugin/invoice/section/create.class.php
 ^  8 of 8 apps/nota/plugin/invoice/section/edit.class.php
Execute : curl -X POST http://demo/hook/deploy/post

SUBMODULE: core
Already on 'master'
 ! File not found - please check path: /var/www/demo/core/apps/nota/assets/css/theme.min.css
 ! File not found - please check path: /var/www/demo/core/apps/nota/assets/js/nt.js
 ! File not found - please check path: /var/www/demo/core/apps/nota/controller.class.php
 ! File not found - please check path: /var/www/demo/core/apps/nota/javascript/nt.invoice.js
 ! File not found - please check path: /var/www/demo/core/apps/nota/plugin/invoice/model/invoice.class.php
 ! File not found - please check path: /var/www/demo/core/apps/nota/plugin/invoice/section.class.php
 ! File not found - please check path: /var/www/demo/core/apps/nota/plugin/invoice/section/create.class.php
 ! File not found - please check path: /var/www/demo/core/apps/nota/plugin/invoice/section/edit.class.php

|----------------[ 65.17K Deployed ]----------------|

**Comment by baldurpan** [comment]
And might I suggest that post hook is called AFTER handling submodules?

**Comment by banago** [comment]
@baldurpan thanks for reporting this. I'm looking into it.
