### ISSUE TITLE
Reconnect if connect is dropped mid-deploymnet

### ISSUE THREAD

**Issue by vicebas** [banago/PHPloy#238]
Actually, I think I need support. I'm uploading a web system, and after a little more than 1300 files, phploy begins to return warnings and then an exception. This only happens to the remote ftp, but the idea was to work exactly for this ftp. Error follows:

```
PHP Warning:  ftp_chdir(): 15 matches total in phar:///usr/local/bin/phploy/vendor/league/flysystem/src/Adapter/Ftp.php on line 289
PHP Warning:  ftp_mkdir(): 15 matches total in phar:///usr/local/bin/phploy/vendor/league/flysystem/src/Adapter/Ftp.php on line 320
PHP Warning:  ftp_chdir(): 15 matches total in phar:///usr/local/bin/phploy/vendor/league/flysystem/src/Adapter/Ftp.php on line 136

Oh Snap: Root is invalid or does not exist: /public_html/deployteste/climas/producao
```

After this error, it stops completely. and when you restart, it did not save any changes to the .revision, and starts uploding all files again

**Comment by banago** [comment]
Please update your message with more details. Did it show any errors or just hanged. What happened?

**Comment by vicebas** [comment]
it shows this and stop on the Oh Snap. And stop workin

```

^ 1340 of 2239 lib/Cake/Console/Templates/skel/webroot/.htaccess
 + Created directory 'lib/Cake/Console/Templates/skel/webroot/css/'.
 ^ 1341 of 2239 lib/Cake/Console/Templates/skel/webroot/css/cake.generic.css
 ^ 1342 of 2239 lib/Cake/Console/Templates/skel/webroot/favicon.ico
PHP Warning:  ftp_chdir(): 15 matches total in phar:///usr/local/bin/phploy/vendor/league/flysystem/src/Adapter/Ftp.php on line 289
PHP Warning:  ftp_mkdir(): 15 matches total in phar:///usr/local/bin/phploy/vendor/league/flysystem/src/Adapter/Ftp.php on line 320
PHP Warning:  ftp_chdir(): 15 matches total in phar:///usr/local/bin/phploy/vendor/league/flysystem/src/Adapter/Ftp.php on line 136

Oh Snap: Root is invalid or does not exist: /public_html/deployteste/climas/producao
```

**Comment by vicebas** [comment]
Is just that. after a great number of files, it give me that warnings and stop. But only if is the remote ftp. In the ftp in the local server, works greatly.

**Comment by banago** [comment]
It seems a change directory issue. I need time to investigate that. Please look in your end too. Thanks.

**Comment by vicebas** [comment]
Seems a closed connection issue. if i could reopen the connection, could solve the issue.

```
 ^ 1179 of 2239 atualizações/outros_sqls/libra_atualizado.sql
 ^ 1180 of 2239 atualizações/outros_sqls/parametrosoperacionais.sql
 ^ 1181 of 2239 atualizações/outros_sqls/tabelas.sql
PHP Warning:  ftp_fput(): Accepted data connection in phar:///usr/local/bin/phploy/vendor/league/flysystem/src/Adapter/Ftp.php on line 210
 ! Failed to upload atualizações/sql_carol_bk.sql.
 ^ 1182 of 2239 atualizações/sql_carol_bk.sql
PHP Warning:  ftp_mkdir(): Accepted data connection in phar:///usr/local/bin/phploy/vendor/league/flysystem/src/Adapter/Ftp.php on line 320
PHP Warning:  ftp_chdir(): Accepted data connection in phar:///usr/local/bin/phploy/vendor/league/flysystem/src/Adapter/Ftp.php on line 136

Oh Snap: Root is invalid or does not exist: /public_html/deployteste
```

**Comment by vicebas** [comment]
Update: Sftp works. The issue Is exclusively related to  ftp protocol

**Comment by NathanGiesbrecht** [comment]
I'd had this problem once a while ago also. Was an FTP server setting timing out after n minutes of "inactivity", even though files were still uploading. One large file would cause the "inactivity", and the connection would be dropped. Not a PHPloy bug.

**Comment by vicebas** [comment]
I had the same conclusion. But my suggestion is, if time out, reconnect, at least one time.

**Comment by jtsternberg** [comment]
Agree, reconnect would be ideal, but I'm also wondering why the .revision file isn't dropped in each directory that is completed as it is completed? This would allow a re-deploy to pick up where it left off instead of having to start completely over again.

**Comment by jtsternberg** [comment]
FWIW, the error I got:

```
PHP Warning:  ftp_fput(): 0 matches total in phar:/.../phploy/vendor/league/flysystem/src/Adapter/Ftp.php on line 211

Warning: ftp_fput(): 0 matches total in phar:/.../phploy/vendor/league/flysystem/src/Adapter/Ftp.php on line 211
```

**Comment by banago** [comment]
@jjeaton reconnect would should not break the loop, otherwise it would start over.

**Comment by pedroadame** [comment]
I like your idea @jtsternberg 
1. Start to upload files.
2. Each directory finished to upload, set a `.tmp_revision` to let PHPloy know that directory is already updated.
3. When `.revision` is touched after a successful deploy, delete al `.tmp_revision`. If connection failed, PHPloy would reconnect and search and delete all `.tmp_revision` if `/.tmp_revision` equals to `.revision` (Upload complete).

**Comment by banago** [comment]
Everybody, this is now addressed.
