### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by tonimain** [banago/PHPloy#239]
Added all credentials
Sftp
IP = 12.34.56.78
Port = 23456
/path/to/key/my-key.SSH
Passphrase = dummy@web.Test

Without success always oh snap could not connect
Im on el capitan 10.11 osx

**Comment by banago** [comment]
@tonimain please use `host` in stead of `ip`.

**Comment by tonimain** [comment]
Lol sorry my fault IP is named host inside phploy.ini
Could it be something else?

My mey is added to config in SSH all Keys are stored in .SSH and the ones with passphrase are stored in keychain for privkey im srtting it to '~/.SSH/mykey'
Althout tested it with the keypass param without success 

Are there some internal error Logs to check?

**Comment by banago** [comment]
Are you following the config correctly? Here is how you use keys: 

    privkey = 'path/to/or/contents/of/privatekey'

Check the config example at readme.

**Comment by tonimain** [comment]
Yep it's exactly as in the sample ini
Scheme = sftp
Host = 13.34.56.78
Port = 22123
User = myuser 
;pass = Pass don't need this dur to privkey
Privkey ='~/.SSH/my-key'
keypass = mypass
Path = /srv/vhosts/mydomain/public/staging

Is the order of those params relevant?

**Comment by tonimain** [comment]
All params are written in lowercase

**Comment by banago** [comment]
No, the order is not relevant. Can you try with full path in stead of the tilde `~/`.

**Comment by tonimain** [comment]
Already tried with '/Users/t.Main/.SSH/mykey'
No success and no errors. Only message is oh snap could not connect :(

**Comment by banago** [comment]
try `phploy --debug` and see what's going on.

**Comment by tonimain** [comment]
thats whats happening 
t.haupt@MBPr-Systeme-THA  ~/Projekte/frs-sbahn-washastduvor/public   develop ●  phploy -s staging --debug
---------------------------------------------------
|                   PHPloy v4.2                   |
---------------------------------------------------
Fetching .revision file

Oh Snap: Could not login with username: web, host: 93.92.135.252
 t.haupt@MBPr-Systeme-THA  ~/Projekte/frs-sbahn-washastduvor/public   develop ● 

**Comment by tonimain** [comment]
that is the config:
[staging]
    scheme = sftp
    user = web
    host = 93.92.135.252
    path = /srv/vhosts/washastduvor/releases/staging
    port = 22123
    privkey = '/Users/t.haupt/.ssh/www_test_dummy_key'
    keypass = web@server.dummy
    branch = develop

**Comment by tonimain** [comment]
Something new from your side ?

**Comment by vytsci** [comment]
Configs have worked before now they are not working.

**Comment by Dean-Wilson** [comment]
Also get this issue. Can connect with no issue via Filezilla but when using exactly the same credentials, phploy fails.  I separated out the config for easier testing but have tried everything at this point and no connection.

    scheme = ftp
    user = user@user.com.au
    pass = passwordinlettersandnumbers
    host = ftp.domain.com.au

The exact same credentials work in filezilla. Thought maybe the @ symbol in the username should be %40 like filezilla handles it but that didn't work either. Also tried host without the ftp and various other adjustments.
