### ISSUE TITLE
Builds

### ISSUE THREAD

**Issue by vytsci** [banago/PHPloy#245]
If this software would have building implemented, I would actually pay for it :D

**Comment by banago** [comment]
How would you like the build process to work? What's on your mind?

**Comment by vytsci** [comment]
Problem is that atm if u are uploading files code can be messed up at some moments in time when someone enters website while deploying. For example you could map revision files and upload it to new release folder instead of their original location and then create symlink to a new release folder. It would be lightweight and perfect for more advanced projects but not such complex so they require very unique building process.

**Comment by raunsbaekdk** [comment]
I actually second this, however a lightweight version could be, that it uploads the files as filename.extension.hashsum fx. After it has uploaded all the files it can rename the files to the original filename, which is significantly faster than; upload, rename, upload rename.

**Comment by vytsci** [comment]
Well Im not the building master :D but i know that when u are uploading files, if someone enter a website it will crash at certain points. That needs to be solved.

**Comment by banago** [comment]
@vytsci and @raunsbaekdk let's continue this discussion over at the previously opened ticket for this topic: #223. Thanks.
