### ISSUE TITLE
problems with deploying submodules

### ISSUE THREAD

**Issue by danielzzz** [banago/PHPloy#247]
hi, I'm trying to deploy a cakephp project. 

when I use phploy without a --submodules flag the vendor/cakephp folder is not uploaded (which I guess is the default behaviour).
but when I enable this flag, a strange thing happens: 
phploy detects just one submodule:
 Found 1 submodules.
   Found submodule no. 
      Scanning for sub-submodules...
      Found sub-submodule no/no.
      Found sub-submodule no/no.
      Found sub-submodule no/no.
      Found sub-submodule no/no.
      Found sub-submodule no/no.
      Found sub-submodule no/no.
      Found sub-submodule no/no.
      Found sub-submodule no/no.
      Found sub-submodule no/no.
      Found sub-submodule no/no.

and then complains about diectories that are above the root dir of  the project:
(my projects is in /media/daniel/lindata/proyectos/myproject)
SUBMODULE: no
No revision found - uploading everything...
 + Created directory 'no/'.
 + Created directory 'no/fatal: Not a git repository: '/'.
 + Created directory 'no/fatal: Not a git repository: '/media/'.
 + Created directory 'no/fatal: Not a git repository: '/media/daniel/'.
 + Created directory 'no/fatal: Not a git repository: '/media/daniel/lindata/'.
 + Created directory 'no/fatal: Not a git repository: '/media/daniel/lindata/proyectos/'.

etc.

do you know what might cause this?
thx, dan

**Comment by banago** [comment]
@danielzzz please grab latest version and re-try. Should be fixed.
