### ISSUE TITLE
PHP Notice 'undefined offset'

### ISSUE THREAD

**Issue by stevefolly** [banago/PHPloy#249]
With version 4.2, using --sync option gives the following output:

`PHP Notice:  Undefined offset: 1 in phar:///[...]/phploy.phar/vendor/league/climate/src/Argument/Parser.php on line 195`

Is this anything to worry about?

`php -i` output attached.

[phpinfo.txt](https://github.com/banago/PHPloy/files/281396/phpinfo.txt)

**Comment by banago** [comment]
@stevefolly are you sure you are on PHPloy 4.2? We had this issue before but it's now fixed. Can you please try again to grab latest version.

**Comment by stevefolly** [comment]
Hi, yes... full output is:

```
$ ./phploy.phar --sync
PHP Notice:  Undefined offset: 1 in phar:///[...]/phploy.phar/vendor/league/climate/src/Argument/Parser.php on line 195
---------------------------------------------------
|                   PHPloy v4.2                   |
---------------------------------------------------

SERVER: production

   No files to upload or delete.

|----------------[ 0.00B Deployed ]----------------|
```

I download phploy.phar from your master branch on the 20th May.

**Comment by stevefolly** [comment]
Downloaded the latest today - still the same issue.

**Comment by banago** [comment]
@stevefolly please grab latest version now. Should be fixed.

**Comment by stevefolly** [comment]
Downloaded and confirmed - notice no longer displayed. Thank you.

**Comment by banago** [comment]
@stevefolly thank you for confirming. :+1:
