### ISSUE TITLE
Default permission changed

### ISSUE THREAD

**Issue by hellodaniel** [banago/PHPloy#251]
After updating to 4.3.1 I've noticed that the default permissions on files is set to 0600, which effectively means all of the files are unreadable to the general public (which is not good for websites).

No permissions have been set in the phploy.ini file.  

See example file after upload here: 
https://www.evernote.com/l/AAfo84Y0NRJMboyN0Q8rCRp-sqG7POR5KPs

**Comment by banago** [comment]
@hellodaniel, right. It's a bug from permissions feature. Fixed. Grab latest version please and thanks for reporting.
