### ISSUE TITLE
Private key wont be read if the path is relative

### ISSUE THREAD

**Issue by mchaelhuang** [banago/PHPloy#252]
The private key wont be read if the path is relative, like `~/key/mykey.pem`

And hopefully we can store `privkey` parameter into `.phploy` file.
Thanks

**Comment by banago** [comment]
@mchaelhuang grab latest version please. This is now addressed. There is no reason to put `privkey` in `.phploy` because it is not sensitive information.

**Comment by mchaelhuang** [comment]
@banago yes it is not a sensitive information, agreed with that.

But i think it is just like a personalisation, some people may store their key on `~/.ssh/mykey.pem`, others (like me) may put it on `~/key/mykey.pem`, and maybe some people just put it on its working directory `./mykey.pem`.

What do you think?
