### ISSUE TITLE
Deploy locally on the same environment?

### ISSUE THREAD

**Issue by irman** [banago/PHPloy#253]
Is it possible to use PHPloy to "deploy" the file locally, just another directory. I don't want to copy and paste, need it to still keep track of the files/deployment/rollbacks. Imagine you're connecting via ftp/sftp to yourself. I found out that you can basically just ssh to yourself. Is there any other "elegant" way to this?

**Comment by banago** [comment]
@irman the 'local' driver would be easy to add. Why would you need such a thing? Trying to understand so I can evaluate if it's worth adding into core.

**Comment by ogrosko** [comment]
@irman Try using symlinks
