### ISSUE TITLE
Deploy in a different directory

### ISSUE THREAD

**Issue by Progi1984** [banago/PHPloy#254]
Hi, thanks for your tool.

I have a repository where I have a directory "site".
I have a server with two directories (staging & production).

I want to deploy my directory "site" (& only it) to the directory staging.

How can I do that ?

Thanks for your answer.

**Comment by Progi1984** [comment]
For excluding, I found the solution : `exclude[]` is my friend.

But I don't find any solution for mapping directories.

**Comment by Progi1984** [comment]
I have found a solution :
* At the root of my project, I exclude all parts to be excluded
* I copy the directory site to staging
* I purge the directory site

```ini
path = .
port = 22
include[] = 'site/vendor'
exclude[] = 'README.md'
exclude[] = 'exclude/*'
exclude[] = 'site/README.md'
copy[] = 'site->staging'
purge[] = 'site'
```

Heavy solution, isn't it !

**Comment by banago** [comment]
@Progi1984 thanks for catching this bug and for the contribution. :+1:
