### ISSUE TITLE
Ask for (s)ftp password if not specified

### ISSUE THREAD

**Issue by amsolucionesweb** [banago/PHPloy#26]
It would be good the console ask for the ftp password if this is blank in the configuration file, this way is can versioning the deploy.ini file without compromising the security of the server.

**Comment by Euphorbium** [comment]
Would it be possible to use system environment variables? Would this be posssible on both windows and unix like systems?

**Comment by banago** [comment]
I don't know much about this unfortunately. Would you like to contribute
that? I would be more then happy to marge that.

**Comment by banago** [comment]
PHPloy now supports asking for password interactively in case it is missing from the `deploy.ini` file. Happy deployment!
