### ISSUE TITLE
Oh Snap: Could not login with username when i use a private key

### ISSUE THREAD

**Issue by strauss69400** [banago/PHPloy#261]
hi,
i download the lastest version in order to use a private key with the prompt passphrase.

so i create my keys with this command : ssh-keygen -t rsa.
my public key is saved in the authorized_keys file of the user and my private key is let in folder '/root/.ssh/id_rsa/.
when i run the upload, i get this error : 

Oh Snap: Could not login with username 'myuser', host: **.**.**.**

i tested my keys with this command : ssh myuser@**.**.**.** -p 30 -i /path/of/my/private/key
and it works!!

here is my phploy.ini : 
`[prod]
    scheme = sftp
    user = myuser
    host = **.**.**.**
    path = /folder/
    port = 30
    privkey = '/root/.ssh/deploy'`

hoping you can help me.thank you very much

**Comment by mikaelz** [comment]
Had the same issue and my hosting provider required RFC4716 private keys in authorized_keys.
Try `sftp myuser@host` maybe your sftp subsystem is not enabled
Maybe http://stackoverflow.com/questions/6377009/adding-public-key-to-ssh-authorized-keys-does-not-log-me-in-automatically helps

**Comment by strauss69400** [comment]
unfortunately, it works when there is no passphrase only!!
