### ISSUE TITLE
Deploy using FTPS with TLS Encryption?

### ISSUE THREAD

**Issue by MarketHubb** [banago/PHPloy#262]
I'm trying to use FTPS as my deployment _scheme_ and when I run `phploy` I am getting the following error:

`Warning: ftp_systype(): Non-anonymous sessions must use encryption. `

Is it possible to run using FTPS and if so, do I need to include a specific configuration option in my .ini file?

**Comment by banago** [comment]
Yes, use `ssl = true` please.
