### ISSUE TITLE
Looking for deploy.ini

### ISSUE THREAD

**Issue by andrew-campher** [banago/PHPloy#264]
When I run phploy its looking for a deploy.ini but the file is called "phploy.ini"

|              PHPloy v3.0.16-stable              |
---------------------------------------------------

Oh Snap: 'D:\xamp\htdocs\xxxx\deploy.ini' does not exist.

**Comment by banago** [comment]
You're using an old version. Why don't you grab latest version? The 3.x
version used `deploy.ini` file name.

**Comment by andrew-campher** [comment]
Thanks - yes appears I used the wrong remote.
