### ISSUE TITLE
Upload vendor directory or ignored files/directories 

### ISSUE THREAD

**Issue by amsolucionesweb** [banago/PHPloy#27]
Since working with composer, vendor directory is in the list of ignored files, so could be a possibility on the first deploy ignored directories will be uploaded.

**Comment by saibotd** [comment]
If you guys need a version with the ability to upload all files and directories, regardless of .gitignore, I've made such a version here: https://github.com/saibotd/PHPloy/tree/feature/secure
The parameter is -o or --others. I don't know if it's good enough for a pull-request though...

**Comment by banago** [comment]
This feature is now implemented. Thanks very much @saibotd - we really appreciate your contribution.
