### ISSUE TITLE
Allow path to be set by environment variable

### ISSUE THREAD

**Issue by jjeaton** [banago/PHPloy#277]
Similar to user, password, host and port, allow the path to be set with an environment variable to keep that information out of the phploy.ini file.

**Comment by banago** [comment]
@jjeaton fix it and make a pull request. :)

**Comment by jjeaton** [comment]
😄  sure, just wanted to add in the issue before I fell asleep and forgot all about it.

It would be really nice to be able to use any environment variable for any value in the `.ini` file. Similar to how Dandelion allows you to use erb in the yaml file: https://github.com/scttnlsn/dandelion.

`password: <%= ENV['DANDELION_PASSWORD'] %>`

Not sure how that would be possible, but would make the configuration very flexible.

**Comment by banago** [comment]
@jjeaton not possible with the current `.ini` setup.
