### ISSUE TITLE
pre-deploy-remote should run from path

### ISSUE THREAD

**Issue by jjeaton** [banago/PHPloy#279]
It appears that the commands that are run during `pre-deploy-remote` get run from my SSH user's home directory, not the path that's defined in phploy.ini. Is there a reason for this? I assumed that any commands I wrote should be based off the deployment path.

**Comment by banago** [comment]
@jjeaton no, that seems like something that needs to be fixed. Do you think you can work on it?

**Comment by jjeaton** [comment]
@banago I could, however I wasn't able to find where the path gets set, any way you could point me in the right direction?

**Comment by ogrosko** [comment]
Check my pull request #295 
If it's ok and it does what you expecting
