### ISSUE TITLE
can't skip[] take settings from git ignore exclude?

### ISSUE THREAD

**Issue by rajnisheu** [banago/PHPloy#284]
Wondering why can't skip files be taken from gitignore or .git/info/exclude. Its a pain setting it up again.
Actually, if its in gitignore, its probably not in the commit but still gets pushed. Am I doing something wrong?
Thanks for a great tool!

**Comment by rajnisheu** [comment]
Basically also struggling a bit with the syntax for skip[] as these directive don't seem to be working

`    skip[] = '/image/cache/*'`
`    skip[] = '/image/cache/*.*'`

tried without the 1st slash too, like so

`    skip[] = 'image/cache/*.*'`

or this
`    skip[] = 'Thumbs.db'`

dev on windows, there are probably several Thumbs.db files which are hard to trace. I am thinking the above directive would prevent any file matching that. Or I'm missing something?
thanks

**Comment by rajnisheu** [comment]
Got mislead by the included ini sample file. Would be good if its replaced.
Issue looked to be that `skip[]` has been replaced with `exclude[]`.
Using exclude looks to be working. Discovered it when I went back to the readme again.

**Comment by banago** [comment]
@rajnisheu yes,  `skip[]` has been replaced with `exclude[]`. I'm sorry you had to go through this and could not back to you earlier.

**Comment by banago** [comment]
Updated include `phploy.ini` file. Thanks again.
