### ISSUE TITLE
Run composer before sync (CI)

### ISSUE THREAD

**Issue by Pimmetje** [banago/PHPloy#285]
I am not sure if it is possible so i hope someone can tell me :)

I would like to use this is in a Gitlab-CI env where i want to run PHPloy to update our staging and production env based on the branch. I think thats doable. But now the question: 
Is it possible to run composer install before syncing and have the files from the vender folder synced to the ftp server?
I have to look if it is possible to run remote migrations. But that's not a issue for me. (I am currently looking for a good tool to sync the files).

This looks like something that does it for laravel: http://packalyst.com/packages/package/fadion/maneuver

**Comment by banago** [comment]
@Pimmetje have a look at this article: http://www.josheaton.org/set-up-free-incremental-deployments-sftp-gitlab-ci-phploy/
