### ISSUE TITLE
custom environment variable for username & password

### ISSUE THREAD

**Issue by Pimmetje** [banago/PHPloy#286]
In the Gitlab-CI envirment is possible to set build variables. I can now do :
    - export PHPLOY_PORT="21"
    - export PHPLOY_HOST="$LIVE_HOST"
    - export PHPLOY_USER="$LIVE_USERNAME"
    - export PHPLOY_PASS="$LIVE_PASSWORD"
The same would be for example stage. 

But it would be nice if this could be set in the ini file. This way the build script stays clean. 
So we could set host to $LIVE_HOST

**Comment by mikaelz** [comment]
There is some env checking https://github.com/banago/PHPloy/blob/master/src/PHPloy.php#L437

Maybe better would be checking for env variables constructed from ini names
From
```
[prod]   # $server
    host = example.com  # $name = $value
    user = example
```
phploy would check for
```
$environmentVar = strtoupper("{$server}_{$name}");
if (!empty(getenv($environmentVar))) {
    $options[$name] = getenv($environmentVar);
}
```

There is already an array of possible settings https://github.com/banago/PHPloy/blob/master/src/PHPloy.php#L351 so it might check the with foreach and prefixed with server name from the ini

**Comment by banago** [comment]
@mikaelz if you improve this, I'd be more than happy to merge it. Let me know.

**Comment by nikolaykovenko** [comment]
Hello, @banago. If @mikaelz doesn't have enough time for this, I can implement this feature. Just let me know guys and I'll start working.

**Comment by mikaelz** [comment]
Hello, sure, if you have time, get into it. Thanks

**Comment by banago** [comment]
@nikolaykovenko yes pleae, go ahead. :+1:

**Comment by nikolaykovenko** [comment]
I started working and I have a question:

Why do we use different constructions inside of foreach ($servers as $name => $options) $servers[$name] and $options?

https://github.com/banago/PHPloy/blob/master/src/PHPloy.php#L408
$servers[$name]

https://github.com/banago/PHPloy/blob/master/src/PHPloy.php#L442
$options['port']


Is there a reason I don't understand?

**Comment by banago** [comment]
@nikolaykovenko that's needed for multiple server support. 

I'm closing this issue to keep things a bit clean. When you have the update ready, just create a pull request. Thanks
