### ISSUE TITLE
Delete is very slow via FTP

### ISSUE THREAD

**Issue by hellodaniel** [banago/PHPloy#288]
Since version 3 (?) the process of deleting files is VERY slow; slower, in fact, than uploading files. The process seems to take 2-10 seconds per file, which will often time out mid-way if there is a large number of deletes. This wasn't an issue in older versions, which used to blitz through the deletes.

Wondering if this is something that others have noticed - would fantastic to speed it up again.

**Comment by banago** [comment]
@hellodaniel are the deletes still taking very long for you?

**Comment by hellodaniel** [comment]
Running 4.5 at the moment - I reckon they're quicker. Just did some timing and it's about 3 seconds for each file over a fast connection. Version 2 used to be super fast. 

I can deal with it but basically if I have more than a hundred files to move/delete it's much faster to do a full deployment (of about 5,000 file repo). 

Surprised no one else has noted this - might be more people are using SFTP than FTP.

**Comment by hellodaniel** [comment]
...yeah 45 seconds per file at the moment! Strange thing is I know it's not a latency issue because the uploads are pretty quick (less than a second each)...

**Comment by banago** [comment]
This might be a specific PHPloy issue. Can you try version 2 on the same server? I think all versions delete files the same, unless there is a pre-check to see if file exists or something.

**Comment by banago** [comment]
@hellodaniel this line might cause the delay: https://github.com/banago/PHPloy/blob/master/src/PHPloy.php#L966

I implemented the check initially because if the file was already delete, i.e. missing the library we use would through an exception and the deployment process would stop. Any idea how to work around this?

**Comment by MetalArend** [comment]
@banago That link points to the meanwhile changed master version.

**Comment by Eduruiz** [comment]
I have several difference on delete speed according to the server I'm deploying to. Some shared hosts are really slow and sometimes if we have a lot of files to delete give some errors in the process, but usually this don't affect good hosts and vps's, maybe there is a server issue holding it back.
