### ISSUE TITLE
diff command issue And ini issue

### ISSUE THREAD

**Issue by rajnisheu** [banago/PHPloy#289]
Issue 1:
For various reasons. I need to run git portable and in windows 10. At the start, phploy seemed to work fine but suddenly started giving git-diff error. At first I thought there needs to be an exe available called **git-diff**.

Getting deeper into phploy code, I realised it was running a command by itself `diff -blah -blah`. It looks the program expects diff to be a command by itself whereas it should be running `git diff -blah -blah` to avoid dependency.

Is there a reason to expect command `diff` would be available? `diff` command by itself is available in *ux environments. If that's the command expected to be run, it should at least be documented.

At the moment I solved it by creating a bat file `diff.bat` in my winpath with the following:

`C:\path\to\portable\git.exe diff %1 %2 %3 %4`

I can not say if its the right solution, but I think it would be better to change the command in the phar to `git diff -blah blah`? Creating a bat and adding to winpath kills the portability.

Issue2:
As documented, I have 2 configs in the phploy.ini [staging] and [prod]. Running `phploy staging` connects to staging BUT also connects to `prod` subsequently. This was verified by adding a `post-deploy-remote[] = "date"` directive in the [prod] setting.

Can this be verified that this is intentional and expected behaviour please? If not, I do not seem to understand the reason for loading and running any other definitions in the file.

thanks

**Comment by banago** [comment]
@rajnisheu please grab the latest version and see if this is still happening. Thanks.
