### ISSUE TITLE
Composer.json points to "bin/phploy" instead of "bin/phploy.phar"

### ISSUE THREAD

**Issue by pies** [banago/PHPloy#290]
The file `bin/phploy` does not exist, so Composer fails to link to it from `/vendor/bin`.

**Comment by banago** [comment]
It is like this because the plan is to move the `.phar` out of the repo and `phploy` there be a simple php file that fires PHPloy.

**Comment by hellodaniel** [comment]
...having the bin file is nice. If it's not much trouble to continue to compile it then fixing the composer issue would be nice.

**Comment by banago** [comment]
@pies and @hellodaniel this is now addressed properly. You can now pull PHPloy in globally or locally using Composer (see Readme). And to update just run: `composer global update` and you'll be on latest version.
