### ISSUE TITLE
Specify folder for source root?

### ISSUE THREAD

**Issue by stevefolly** [banago/PHPloy#292]
Hi,

Is there any way to specify a folder in the source repository as the root for uploading?

Example:
- repo\
  - phploy.phar
  - phploy.ini
  - README.md
  - html\
    - index.html
    - page2.html

I want to copy everything in html to the destination, and ignore everything outside of html\  Is this possible?

Thanks

**Comment by mikaelz** [comment]
I would try the following in phploy.ini :)
```
exclude[] = '/'
copy[] = 'html->html'
```
or
```
include[] = 'html/'
exclude[] = '/'
```

**Comment by stevefolly** [comment]
Thanks for the suggestions @mikaelz , unfortunately they don't work as I would expect.  I don't think I was clear enough in my original question:  the FTP destination is (for example) `/var/www/httpdocs` this is where `index.html` would reside. I want the content of `html/` to appear in `httpdocs/`.

What I've tried, and your suggestions, end up still with an unwanted `html/` folder. The copy (`html->.` was better) did copy the files to the right place, but it still left the `html/` folder and it didn't synchronise properly - i.e. the copy didn't remove any old files that were no longer required.

Interestingly, I've found the tool 'lftp'  https://lftp.yar.ru/ - that can do mirroring from any subfolder, I'll give this a go.

**Comment by mikaelz** [comment]
You could create some custom command
In one of my projects I have the following:
```
post-deploy[] = 'scp .git/refs/heads/master user@example.com:sub/project/web/.revision'
```
This is `scp` from local to remote. You might replace it with rsync (but it's unsecure)

**Comment by paulmartin84** [comment]
I don't think we should have to work around this, This should be built in as an option, Its very common to have a docroot or webroot in a git repo with other directories outside this that you would never want to ftp to the webserver, would be nice to just have a source option. The exclude option doesn't solve this as you end up with the docroot folder on the server instead of its contents.

**Comment by paulmartin84** [comment]
@stevefolly actually looking at the 3.x branch the instructions show:
; You can specify a list of patterns of files to be uploaded.
; Only files that match at least one of the patterns will be uploaded to the server.
; If a list of include patterns is not present, all files are considered
; by default (as if include[] = '*' was specified).
include[] = 'public_html/*'

Going to try this out, but this looks like it should work.

**Comment by paulmartin84** [comment]
Looking at https://github.com/git-ftp/git-ftp it has options:
```
-remote-root : Specifies the remote root directory to deploy to. The remote path in the URL is ignored.
--syncroot : Specifies a local directory to sync from as if it were the git project root path.
``` which solves my problem, so will use that for now

**Comment by Eduruiz** [comment]
I would love this option too, in one of my projects I and up setting up a rsync deploy with gulp to bypass this.
I have the fallowing:

- project
 -.git
 - app
 - dist

and I want to deploy only the `dist/` folder contents (but not the folder) into a `www` folder on the server.

**Comment by anvart** [comment]
@mikaelz 
```
include[] = 'html/'
exclude[] = '/'
```
Is not behaving as expected. Instead I used the following:
```
exclude[] = '*'
include[] = 'html'
```
But of course it still requires to have this extra subdirectory on the server, so +1 for the option.

**Comment by bart-webleads** [comment]
I also need this option!

My project document root is never the same as the hosted/remote document root.
My local document root is 'htdocs' and my hosted/remote document root is 'www'

**Comment by flowdee** [comment]
My repository always includes a web/ folder representing the root on the webserver. So it would be very cool to set the repo web/ folder as source root 👍

**Comment by banago** [comment]
Hey everyone. It seems I've not had a good grasp of what this issue was before. Special thanks to @plashenkov for clarifying this to me on issue #304. 

I see two ways of implementing this, 1:

    only[] = 'web/'
    copy[] = 'web/->/'

Or 2:

    map = 'web/'

`map` might not be the best term, but the idea is that it will play only one role, map a directory from the repo to the web root which will be the only thing to be uploaded. Which is better?

**Comment by plashenkov** [comment]
`only[]` looks like a solution too.
But it's just logically different from the possible `syncroot` option.
`only[]` will allow to deploy only specified directories and ignore everything else—right? That's super useful too.
`syncroot` option will completely redefine the root to deploy to a server (by default it is a git repo root for now).
It seems to me that it would be great to have both options—only[] and syncroot (or another name).

**Comment by plashenkov** [comment]
For the `syncroot` (or `map`) option we should decide how to define paths in ini—they have to be relative to a git repo root or to a new sync root.

**Comment by plashenkov** [comment]
While `only[]` looks very useful for me, I would vote for `syncroot` (if to select only one which is better). It's clean and without remote copyings and other magic :)

**Comment by Eduruiz** [comment]
I like the `syncroot` option too, I'm using rsync for this, with rsync I have to set 2 options, `root` and `destination`, so it will basically be the same thing, but in phploy will be `path` and `syncroot`. 

and for the path, I think they should be relative to the git repo, 'cause is usually where my `phploy.ini` file is, so looks better to me.

**Comment by lekkerduidelijk** [comment]
I'd also really like this option. My static projects have a `source` and `build` folder and only the latter should be deployed. Reading over the options `syncroot` makes the most sense to me since git-ftp uses it as well.

**Comment by lekkerduidelijk** [comment]
In addition I've managed to create a workaround for now.

My liveserver tree looks like:
```
- error_docs
- httpdocs
- logs
```
I deploy my `build` folder to this root and then use the copy to move it over the httpdocs folder.
```
[production]
    scheme = ftp
    port = 21
    exclude[] = '*.*'
    include[] = 'build'
    copy[] = 'build->httpdocs'
```

**Comment by banago** [comment]
I don't like the `syncroot` naming, it's not clear what it does. I'd prefer `maproot` because what we are actually doing is mapping the root to something else.

    [production]
        maproot = build

What do you guys thing of `maproot`?

**Comment by plashenkov** [comment]
Is `maproot` more clear than `syncroot`? I (subjectively) do not think so :)
`syncroot` means a root to be synchronized with a remote. It's clear for me.
Nevertheless it's just a matter of personal preference. Just name it as you like it (you are the developer :).

**Comment by banago** [comment]
@plashenkov I'm the main developer, but I don't build PHPloy to only use myself. I take your opinions and contributions very seriously, so thanks again. :+1:

**Comment by Eduruiz** [comment]
I think `root` is enough, but is really a preference thing I think, I am used to read `root` 'cause `rsync` use it. if I have to "defend" my point I would say that the configuration is all about "deploy", we don't have to specify things like `sync_exclude` or `sync_include` for example, the `sync` part is implicit because `phploy` is a deploy/sync application.

**Comment by banago** [comment]
@Eduruiz couln't agree more. I like it just `root` too for the same reason. Thanks for your input.

**Comment by lekkerduidelijk** [comment]
+1 for `root`

**Comment by RobertCordes** [comment]
+1 for `root`. Would love to have this option.

**Comment by tw-360vier** [comment]
also would love to see the `root` option!

**Comment by banago** [comment]
Everyone, new news -- this feature is finally implemented. I used `base` as a less confusing naming. 

Usage:

    base = 'www/'

Please grab it here to test, until I officially release it: https://github.com/banago/PHPloy/tree/feature-base

@stevefolly, @mikaelz, @paulmartin84, @Eduruiz, @anvart, @bart-webleads, @flowdee, @lekkerduidelijk, @RobertCordes, @tw-360vier

**Comment by plashenkov** [comment]
It's fantastic

**Comment by rodrigobutta** [comment]
Hi! I think that "base" parameter might not be working or i'm missing something here.

I'm on windows, and phploy it's uploading the root folder (in the remote root) instead of the "build" folder, despite of beign setted base='build/'

Using v4.8.5

I'm doing something wrong? Thanks

![image](https://user-images.githubusercontent.com/203718/39002912-04487efa-43d0-11e8-887a-97f306d9c938.png)

![image](https://user-images.githubusercontent.com/203718/39003147-a0a867a6-43d0-11e8-8be5-95d92a0e3e10.png)

![image](https://user-images.githubusercontent.com/203718/39003187-b12c5e2a-43d0-11e8-8538-a644fca8d05a.png)

**Comment by aps90** [comment]
hi @rodrigobutta  Could you find the problem? The same happens to me, thanks!

**Comment by mordonez** [comment]
Same here!

**Comment by banago** [comment]
I've totally missed this. Will check this weekend hopefully.

**Comment by ainarend** [comment]
I can confirm that the issue still exists with base. Installed from composer and tried to get the base setting to work (with the trailing /), but unfortunately, the base setting was ignored and project root was still used instead.

**Comment by ekersten** [comment]
@rodrigobutta did you find a solution for this? I'm really in a hurry with a very important project!
