### ISSUE TITLE
Use of undefined constant FTP_BINARY

### ISSUE THREAD

**Issue by Turbo123** [banago/PHPloy#296]
I´m getting this strange error when I run PHPloy for a project.
Any clue why? I have set up phploy.ini for my project.

Notice: Use of undefined constant FTP_BINARY - assumed 'FTP_BINARY' in phar://E:/wamp64/www/PHPloy-master/bin/phploy.phar/src/Connection.php on line 87

**Comment by folkevil** [comment]
i got same issue

**Comment by glockenmeier** [comment]
I think it's coming from a library PHPloy uses (Ftp Adapter).
Traced it to [this line](https://github.com/banago/PHPloy/blob/c521f9f2dad82a065c4a2b6f2a03a1f91f98512c/src/Connection.php#L5) `use League\Flysystem\Adapter\Ftp as FtpAdapter;`
[and this one](https://github.com/thephpleague/flysystem/blob/0165294685dc83e521a46e0df2ff6b8bd4df4369/src/Adapter/Ftp.php#L20) `protected $transferMode = FTP_BINARY;`

**Comment by andreibarbuta** [comment]
For those who use Windows ( 10 ) and run into this issue:
1. Change your PHP in PATH (System > Advance System Settings > Enviroment Variables) from PHP 7 to PHP 5.6
2. Relaunch your CMD prompt or whatever you are using for command line

**Comment by Eduruiz** [comment]
I solved it by simple enabling the ftp extension on my php.ini

**Comment by Excelautomation** [comment]
As @Eduruiz said. Adding the following to php.ini worked for me.

`extension=php_ftp.dll`

**Comment by mathmul** [comment]
Or in my case, using PHP 8.x, the line I uncommented in php.ini is `extension=ftp`.

If you're using Laragon you'll find the file in `C:\laragon\bin\php\[PHP 8 folder]\php.ini`.
