### ISSUE TITLE
revision does not get uploaded

### ISSUE THREAD

**Issue by bart-webleads** [banago/PHPloy#297]
phploy keeps uploading all files.

I noticed that the ".revision" file does not get uploaded. The reason is that my hosting company does not allow me to write files in the "root". I can only write files in the "www" folder.

- Phploy should write a warning if this file can not be uploaded.
- Could the location of the revision file be made configurable?

**Comment by banago** [comment]
Good point. Just curious, why are you deploying to your root directory? Do you deploy other files to that directory and do they upload alright?

**Comment by bart-webleads** [comment]
I always create projects that contain a 'htdocs' directory. This is the website root. With PHPloy I cannot "map" my project htdocs folder to the live FTP 'www' folder. So that is why I cannot use PHPloy.
When I was trying different things, I came across the "revision does not get uploaded" problem.

**Comment by banago** [comment]
@bart-webleads I understand. Any particular reason why you use `htdocs` locally and `www` on the server?

**Comment by bart-webleads** [comment]
I have used htdocs in the past and I just kept on doing that.
And each hosting provider uses a different folder for it, like httpdocs, web, www, ...
So changing it to match my hosting provider is useless.

**Comment by banago** [comment]
Thanks for the details. Directory mapping might happen since it's being requested a lot. Let's move the conversation here: #292.
