### ISSUE TITLE
upload non indexed files when indexed files changed

### ISSUE THREAD

**Issue by stoutZero** [banago/PHPloy#301]
CMIIW

I have a single folder that is generated by `laravel-elixir` via `gulp`, the resulting build files will _never_ be indexed,  
but the source files that will never be uploaded to any non git hosting server _are_ indexed.

Right now this line on `phploy.ini`:
```ini
include[]='public/build/'
```

means anything on that folder is always uploaded, regardless of whether there are any file that has been changed

Are there anyway to trigger file upload inside build dir _IFF_ there are any file changed in its corresponding source dir?

**Comment by banago** [comment]
That's a good point. Unfortunately that kind of mapping does not exist at this point. Sorry.

**Comment by pedroadame** [comment]
+1 I came here searching exactly that. Uploading vendor dir is expensive in every deploy.
