### ISSUE TITLE
Add multithreading

### ISSUE THREAD

**Issue by krzysztofp** [banago/PHPloy#302]
At the moment I'm uploading my project to the production server. It's overall 6000 files and this is my first deploy. Is there any way this process can be done multithreaded?

**Comment by marcus-at-localhorst** [comment]
I believe you can do the initial upload with a FTP program of your choice and then use the `phploy --sync='hash'` command to create the revision file on the server.
See https://github.com/banago/PHPloy/issues/14

**Comment by krzysztofp** [comment]
@marcus-at-localhorst - wow, that's good to know - many thanks. To be honest - I already had all files on the server and right now thought it would be cool to start using git (and FTP unfortunately) for improved  - maybe some kind of simple detection tool would be a good idea (for example: "Hey, it looks like the files you're trying to upload, already exist on the server - are you sure you want to upload them again?)

Another idea to consider - if an upload has started and after 2 -3 hours the internet connection broke for 10 minutes, it should not start from the beginning. I had this situation 3 times yesterday. It should remember when it stopped and continue from that moment.

**Comment by glockenmeier** [comment]
@krzysztofp had a similar issue needing to re-upload a project with lots of files. Using FTP to upload the files is too slow and error prone. Although FileZilla kept tabs on failed uploads it doesn't always work outright. So instead I uploaded a ZIP file and created a simple PHP unzip script.

Would be a nice to have if PHPloy could do similar zipping say, for initial upload, generate unzip script, then unzip server side and finally delete server script.

**Comment by banago** [comment]
Multithreading upload is cool and I'd be more than happy to merge any pull requests, but I don't have the time to implement this in the short-term.

**Comment by CodeBrauer** [comment]
@glockenmeier This is my current workflow and I have a basic command set for this: Maybe this could be even integrated or built on top of phploy for bigger project inits:

```bash
echo "<?php echo shell_exec('unzip init.zip && rm init.zip unzip561.php');?>" > unzip561.php
zip -r init.zip . --exclude=*.git*
curl -T init.zip ftp://example.org/path/to/deploy --user user:pass
curl example.org/unzip561.php
echo 'Init Upload finished!' | terminal-notifier -sound default
```

So I use this command set on macOS, but should work everywhere (except [terminal-notifier](https://github.com/julienXX/terminal-notifier) - but I've seen there are already easy to implement cross plattform notifier like [node-notifier](https://github.com/mikaelbr/node-notifier))

Quick explanation (per line):

1. Create a unzip-php-file so it is in the uploaded zip-file
2. zip current working directory without `.git` directory
3. upload the zip file to the server
4. call the unzip file via curl to start extracting the zip file - which also deletes the zip and itself
5. Tell me it's finished

**Comment by banago** [comment]
Due to limitation of [Flysystem](https://github.com/thephpleague/flysystem), the underlying library that PHPloy uses, multi-threading is not possible at this time. We will be exploring the possibility of zipped deploys here: #259.
