### ISSUE TITLE
Filenames with spaces fail to delete via FTP

### ISSUE THREAD

**Issue by hellodaniel** [banago/PHPloy#303]
Receiving errors in the console when trying to move/remove files with spaces. 

e.g.:  ```! File not found - please check path: /project/html/Overview.md```  when the path is actually something like ```/docs/01 Guides/Overview```

Arguably spaces are not a good idea (and I've since renamed all files to have underscores) but they are perfectly valid and should probably work. 

Interestingly, creating files with spaces is fine, it's only moving/deleting and updating that fails.

**Comment by banago** [comment]
Point taken, thanks for reporting.

**Comment by banago** [comment]
@hellodaniel I ran some tests with files and directories with space in the name and all worked well. This is either a different underlying problem or it has been fixed somehow. Please pull the latest version and try on your end. Closing it for now.
