### ISSUE TITLE
Add an option to deploy a subdirectory only

### ISSUE THREAD

**Issue by plashenkov** [banago/PHPloy#304]
Hello!

I am not sure you will get notifications from the [closed issue](https://github.com/banago/PHPloy/issues/282), this is why I created the new one.

I've tried the `copy[]` param and it looks like this is not a solution for this case.
Often it is necessary to deploy just one subfolder. There can be many other extra files and folders in the repository and they simply should not be deployed. There can be graphic files, non-compiled sources, etc. They can be large, they can be small but countless. They can be later added, removed — and they are not to be deployed to a server. Only one subfolder is intended to be deployed.

And sometimes web root on the server is the only place where to deploy to.

I believe the special option is necessary — `syncroot` or something like that.

Thank you

**Comment by banago** [comment]
@plashenkov that's interesting. So, you are saying there are cases when you need to deploy only one subdirectory from your repo and that subdirectory is actually the web root directory? 

How would something like this work:
    only[] = 'dist'
    copy[] = 'dist->/'

I'm thinking of `only[]` so it can be used for more then one subdirectory where needed and you can copy the right directory to the root folder then `/`. 

Let me know.

**Comment by banago** [comment]
Let's continue this over at #292

**Comment by plashenkov** [comment]
It looks like a solution too.
But it's just logically different from the possible `syncroot` option.
`only[]` will allow to deploy only specified directories and ignore everything else—right? That's super useful too.
`syncroot` option will completely redefine the root to deploy to a server (by default it is a git repo root for now).
It seems to me that it would be great to have both options—`only[]` and `syncroot` (or another name).
