### ISSUE TITLE
Phar without require-dev

### ISSUE THREAD

**Issue by plashenkov** [banago/PHPloy#305]
I've found that the latest bin/phploy.phar in the master branch is extra-small (368 KB). It came with the commit from @ogrosko.

It looks like it was built with `composer --no-dev install`.

Currently executing ./build produces much larger file (~1.2 MB), and this line: https://github.com/banago/PHPloy/blob/master/build#L29 for some reason does not prevent from inclusion of complete vendor dir to the final phar.

Phar from 4.5 (https://github.com/banago/PHPloy/blob/4.5/bin/phploy.phar) is 2.44 MB.

Sure it's not the most important thing but it's great when resulting phar is beautifully small and free from unnecessary dependencies. Please take into consideration if possible :)

**Comment by banago** [comment]
@plashenkov this is a great thing. I've not updated the build script to exclude dev stuff. Are you saying that `composer --no-dev install` will produce a `.phar` file too?

**Comment by plashenkov** [comment]
Yes, if we add `--no-dev` here:
https://github.com/banago/PHPloy/blob/master/build#L14

We will get much less dependencies in vendor. And as a result phar will be very small.

**Comment by banago** [comment]
Right. That will work only on fresh installs. In my case it won't do much. I see your pain and I'll look into this. I also want us to have a lean `.phar` file.

**Comment by banago** [comment]
@plashenkov this is now addressed. The current Phar is around 400kb.
