### ISSUE TITLE
Deploy include[] only when some file is changed

### ISSUE THREAD

**Issue by plashenkov** [banago/PHPloy#306]
I've noticed that files included using `include[]` option are deployed always, on each deploy.
Since PHPloy is written in PHP, it will be very often used to deploy PHP projects. Modern PHP projects use composer, which uses vendor folder. Best practices say to not include vendor dir to repository, however it is necessary on the server. This is why we include it using `include[]`. Vendor folder often is very expensive. Due to this every deploy process becomes long and tedious—even if vendor folder was not even changed.

This is how git-ftp solves this problem:
`vendor/:composer.lock`
(see here: https://github.com/git-ftp/git-ftp/blob/develop/man/git-ftp.1.md#syncing-untracked-files)

I.e. you can specify the file after a colon—if git says that this file was changed we need to redeploy included[] folder.

Something like this would be very nice to have in PHPloy. That file can be optional. If it is not specified then the behavior should be as it currently is. Deploying for the first time should deploy the folder (or file) completely.

If I am not mistaken that functionality can be implemented here: https://github.com/banago/PHPloy/blob/master/src/PHPloy.php#L580
(sure, if to use the same or a similar approach as git-ftp uses).

**Comment by banago** [comment]
@plashenkov I like that idea. That would work great for the vendor folder. What would happen when you include other files or folders you say?

**Comment by plashenkov** [comment]
> What would happen when you include other files or folders you say?

Sorry I cannot understand the question (due to my English probably).

The whole idea is that if something is specified after a colon then we need to redeploy the object (a file or a folder specified before colon) only if that something is modified. If nothing specified after a colon then we just deploy the object (file or folder) every time, on each deploy.

```
include[] = 'app/vendor:app/composer.lock'
include[] = 'some-other-dir'
include[] = 'css/styles.css:scss/styles.scss'
```

Here `vendor` dir is deployed only when `composer.lock` has been changed; `some-other-dir` is deployed always; `styles.css` file is deployed only if `styles.scss` has been changed.

We can also use another separator (double colon `::` or maybe `|`).

Sorry if I am unclear somewhere.

**Comment by banago** [comment]
You have understood my question correctly. Pairing the included file/folder with another one that's tracked by git seems a great idea, I really like it. This would be a great feature. Is this something you can help with? I'm quite busy a the moment and there are a couple of other issues I'd like to tackle first. I'd really appreciate your contribution.

**Comment by plashenkov** [comment]
Yeah I will try to do that. I am busy for now too — but on the next week I will be able to do that.

**Comment by plashenkov** [comment]
Hello! Any news here? :)

**Comment by swiffer** [comment]
would be awesome to have this merged and released soon.

what happens in case of changed composer.lock currently ? will existing files be deleted and then uploaded from scratch or will contents be overwritten?

**Comment by plashenkov** [comment]
It does not delete now, just uploads on top of existing directory.
That is a good remark—ideally the folder should be deleted first, then reuploaded from scratch. Right? Will it always and unequivocally be a better scheme?

**Comment by swiffer** [comment]
i think at least for vendor directory this is the way to go, don't know if there are other use cases

**Comment by plashenkov** [comment]
Yes, it's true, but I am not sure we may hardcode it for vendors, we need to implement it in a generic way. It seems to me it is always better to delete/reupload for the case of a folder (for a single file it is not necessary to delete it first). I'll try to implement this when I have free time. Or maybe somebody can help—that would be great.

**Comment by swiffer** [comment]
Hey, think your PR has been merged but this discussion seems still to bei Open. Any Change to See this in an additional Update? If content of a folder depends in a File i think it is save to delete Files before uploading them again.

**Comment by banago** [comment]
@plashenkov and @swiffer please grab 4.7 release to test this out. Thanks very much for your input and pull requests.
