### ISSUE TITLE
Ability force-push all files.

### ISSUE THREAD

**Issue by jtsternberg** [banago/PHPloy#307]
Occasionally it's prudent to do a "force-push" to wipe out all files in the repo on the server and replace.

**Comment by lekkerduidelijk** [comment]
Remove the .revision file and you're good to go.

**Comment by banago** [comment]
@jtsternberg and @lekkerduidelijk this feature is now implemented. Usage:

    phploy --fresh

**Comment by jtsternberg** [comment]
nice, thanks!

**Comment by lekkerduidelijk** [comment]
Nice one @banago! What's your plan for #292? Do you have the time to work on that as well?

**Comment by banago** [comment]
@lekkerduidelijk I'm making some time for these tasks. That's next on the list. Let's see how long it takes.
