### ISSUE TITLE
PHPLOY_PATH overridden by default path value

### ISSUE THREAD

**Issue by ttgrules** [banago/PHPloy#309]
$options['path'] has a default value.
The logic to get the path from PHPLOY_PATH does not activate since $options['path'] is not empty.

**Comment by jjeaton** [comment]
I was just bitten by this as well (and I added this feature!) :(

**Comment by banago** [comment]
So, this line needs adjustment?

```php
if (empty($options['path']) && !empty(getenv('PHPLOY_PATH'))) {
```
Who's creating a pull request? :smile:

**Comment by jroedel** [comment]
Maybe it's better to disable the path in the configuration file so that it doesn't affect anyone using Phploy in production. Besides, it might make sense for some people who have multiple projects that th configuration overrides a system wide variable.

**Comment by ttgrules** [comment]
Setting the path as empty in the config does work around this issue. Modifying it to check for empty $options['path'] or $options['path'] == "/" or removing the default would only backfire if someone is using their root directory as their repository. Not sure if that's a big issue or not.

**Comment by banago** [comment]
@ttgrules this is now fixed according to your suggestion.
