### ISSUE TITLE
Git checkout returns many modified files even after --sync

### ISSUE THREAD

**Issue by gogy27** [banago/PHPloy#312]
Hi,

I have a little problem with deploying via phploy.
When I run the script it ends up with "Oh Snap: Stash your modifications before deploying." message.

I was going through the code a little bit and I found this symptoms:
1. The exception is fired because of [PHPloy.php line 838](https://github.com/banago/PHPloy/blob/master/src/PHPloy.php#L838) 
There is:
```
if (isset($output[1])) {
    if ($output[1][0] === 'M') {
        throw new \Exception('Stash your modifications before deploying.');
    }
}
```
I don't know why you are checking just 2nd line of the output (i am getting about 250 changed files and the "M" flag is in the different lines.

2. Even when i run `phploy --sync` and then I run `phploy` I still get almost same list of modified files (mostly deleted or modified).

3. Ok so I decided to comment out the specific lines which fire the exception and the `phploy` is working fine. `phploy` command say "No files to upload or delete." after `phploy --sync`. Also when I made some changes, it deploys correct files and ignores the files which is in `$output` variable after `$git->checkout`.

I am using phploy almost a year but this is the first time when I run to some strange problem. Might by the problem because I started using rebasing instead merging?

**Comment by banago** [comment]
@gogy27 almost one year later, huh? Sorry about this. Has this been resolved yet? I'm closing this for now, but do let me know.

**Comment by gogy27** [comment]
Hi @banago, I had this issue only in one of my many projects and I fix it as I wrote above.
Maybe you should just check if checking only `$output[1]` is enough or you need to check also other items from `$output` if they have the 'M' flag.

**Comment by danielzzz** [comment]
hi, I have a branch in my project and I'm trying to upload changes from this branch (which is my working directory too)
but I am getting this "Stash your modifications before deploying"
What might be the reason? all the modifications are commited

thanks

**Comment by danielzzz** [comment]
I am answering to myself:
there were untracked files from submodules on master, which prevented the branch to be uploaded.
not sure if anything can be done about it?

**Comment by jan-koch** [comment]
I have this issue too, even though all branches in my Github repo are updated and `git status` shows no files that are untracked or changed.
