### ISSUE TITLE
Allow for arbitrary options in the .phploy file

### ISSUE THREAD

**Issue by jroedel** [banago/PHPloy#317]
Hey, thanks for this great script!
Do you think we could allow for arbitrary options in the `.phploy` file?

The use case is this:
I need to call a webhook wget command though the `post-deploy[]` option, but it needs an api key which I can't submit to source control. 

**Proposed solution**: The final option set just be a merge of the `.phploy` and `phploy.ini` file so that any sensitive information can't be placed in `.phploy`.

Here is the full command (I got this idea from the README, thanks!):
`post-deploy[] = "wget https://example.com/clear-cache?key=xxxxxxxxxxxxxxxxxxxxxx --spider --quiet"`

**Comment by mikaelz** [comment]
You might read the API key with a shell script into an environment var and use it
`post-deploy[] = "./bin/export_envs.sh && wget https://example.com/clear-cache?key=$ENV_API_KEY --quiet"`

**Comment by dl1ely** [comment]
@mikaelz I think chaining shell commands in a single `post-deploy[]` won't work as `escapeshellcmd` will escape the `&` before executing that line. But the two commands can be joined in a single shell script file and called from `post-deploy[]`.

**Comment by banago** [comment]
@jroedel environment variables are your best bet here as per @mikaelz example. Let's continue this at #321 about command chaining.
