### ISSUE TITLE
Pre- and post- text in phploy.ini

### ISSUE THREAD

**Issue by mikaelz** [banago/PHPloy#319]
It would be great to define
`pre-text = "Deploying to $HOST"`
and
`post-text = "Deploy finished, check at http://example.com"`
Just output like `post-deploy` echoes executed command

**Comment by dl1ely** [comment]
What keeps you from adding `echo` commands to `pre-deploy` and `post-deploy`?

**Comment by banago** [comment]
@mikaelz it's almost one year later, sorry. I'm not sure what you are looking for here, new arguments?

**Comment by mikaelz** [comment]
@dl1ely suggestion should work. Thanks
