### ISSUE TITLE
Logging PHPloy Output

### ISSUE THREAD

**Issue by SimonEast** [banago/PHPloy#32]
I often want to check when I last made a deployment, and a log file would be really handy.  It's a relatively easy patch to enable logging to a text file (in addition to output on the screen), which I'm keen to write soon.  But my only question is how it should be configured in deploy.ini.

* Should you specify a log file *per* environment?  Or one overall?
* How can we make configuration work with both quickmode and verbose mode?
* Should the filename accept [strftime-compatible](http://www.php.net/manual/en/function.strftime.php) date variables, perhaps like: `deployments %y %m.log`?
* Should you be able to specify the level of detail/verbosity written to the log file?

**Comment by banago** [comment]
Logging from CLImate: https://github.com/thephpleague/climate/pull/60#issuecomment-76657014

**Comment by banago** [comment]
Basic logging is now implemented. Turn it on by adding `logger = on` to config file and check out the results at `phploy.log`. 

I'd appreciate your feedback on this very much.
