### ISSUE TITLE
several cli commands 

### ISSUE THREAD

**Issue by gulaandrij** [banago/PHPloy#321]
I cant use command like "cd frontend && npm run build", because in function exec this string prepare with function escapeshellcmd to "cd frontend \&\& npm run build" https://github.com/banago/PHPloy/blob/master/src/Git.php#L48

How can I use commands like that?

**Comment by gulaandrij** [comment]
ping @banago

**Comment by lekkerduidelijk** [comment]
You should use `post-deploy-remote[]` and make sure you have ssh access. 
I use something like `post-deploy-remote[] = "sh post-deploy.sh"` and it works smoothly.

**Comment by gulaandrij** [comment]
@lekkerduidelijk first of all I need run my commands localy. Remote commands dont have this issue. I thing there is no need to use `escapeshellcmd` in this case

**Comment by lekkerduidelijk** [comment]
Personally I find it better to have the `escapeshellcmd` in place. Should you really need it one should consult it's sysop to allow the needed commands in the `php.ini` imho.

**Comment by gulaandrij** [comment]
its not a disalowed commands, its just `cd frontend && npm run build`, but `escapeshellcmd` prepare it to `cd frontend \&\& npm run build`

**Comment by dl1ely** [comment]
@gulaandrij Each line of `post-deploy[]` is executed in a separate sub shell, so splitting your two commands in two `post-deploy[]` lines does not help. Getting rid of `escapeshellcmd` might be feasable as you are controlling the values that go inside the `exec` call, so security risks are controllable. But if `escapeshellcmd` is here to stay, the only way seems to be to call a shell script that wraps your complex call. But to be honest, i see no added value to escape the command you have control over by yourself. It is meant to prevent bad things for commands or parts of commands that come from external sources, so it rightfully prevents exactly what you need: chaining commands. But in this context that is only a limitation without advantages.

@banago What do you think? `escapeshellcmd` only prevents rightfully crafted shell commands from executing. There is no way to get external non-controlled values inside the `exec`ed string.

**Comment by banago** [comment]
@dl1ely I see no added value from `escapeshellcmd` either and since commands don't come from users it makes sense to remove it.

**Comment by banago** [comment]
Everyone, this is now fixed. Happy deployment!

**Comment by gulaandrij** [comment]
great, tnx
