### ISSUE TITLE
post-deploy[] that use both single and double quotes

### ISSUE THREAD

**Issue by skinpixel** [banago/PHPloy#323]
The example here is using curl to send a message to Slack:
```sh
curl -X POST --data-urlencode 'payload={"username": "example", "text": "Website has been deployed to Master", "icon_emoji": ":package:"}' https://hooks.slack.com/services/HOOK-URL
```
The problem is that the string requires both single and double quotes, and fails when this is inside a post-deploy[] or a post-deploy-remote[] like so:
```sh
post-deploy[] = "curl -X POST --data-urlencode 'payload={"username": "example", "text": "Website has been deployed to Master", "icon_emoji": ":package:"}' https://hooks.slack.com/services/HOOK-URL"
```
It would be great to be able to use post-deploy with slack, but unfortunately this doesn't work.
There might just be something I've missed, or perhaps the code could instead find everything between the first and last double quote on that line instead of the first and next.

**Comment by mikaelz** [comment]
It's executed via `postDeploy()` at https://github.com/banago/PHPloy/blob/dd40770401387f9e238ab73c79a3cae2461121b9/src/PHPloy.php#L1299-L1309

I would try the following

```
post-deploy[] = 'curl -X POST --data-urlencode \'payload={"username": "example", "text": "Website has been deployed to Master", "icon_emoji": ":package:"}\' https://hooks.slack.com/services/HOOK-URL'
```

**Comment by skinpixel** [comment]
unfortunately using back slashes won't work, as they are not recognised by the command line to escape characters in that way.

**Comment by dl1ely** [comment]
According to the comments in http://php.net/manual/de/function.parse-ini-file.php there is no easy way to overcome the parsing limitations of the ini file parser. I submitted a PR that uses http://php.net/manual/de/function.parse-ini-file.php#70847 as a workaround to allow for insertion of literal quotes and double quotes in the ini file values.

**Comment by skinpixel** [comment]
Thanks @dl1ely That may just do the trick, will try your PR when I get a chance and let you know if I have phploy talking to slack!

**Comment by dl1ely** [comment]
@skinpixel 
```
post-deploy[] = 'curl -X POST --data-urlencode 'QUOTE'payload={"username": "example", "text": "Website has been deployed to Master", "icon_emoji": ":package:"}'QUOTE' https://hooks.slack.com/services/HOOK-URL'
```
should do the trick. I know it is ugly, but at least it works.
