### ISSUE TITLE
Does PHPLoy do some sort of local caching if installed via composer?

### ISSUE THREAD

**Issue by JayWood** [banago/PHPloy#324]
We're using PHPLoy to handle incremental branch-specific deploys in our Jenkins pipeline. The pipeline is setup to deploy for only `master`, `prod` and `staging` and isn't setup to remove those directories.

We're doing a fresh checkout of the revision which triggered the job, and I've checked the change sets right before a deploy just to make sure things well... changed.

But for some reason, unless we run `deleteDir()` to remove the jenkins workspace, phpLoy will not deploy files, despite the log stating it did. Checking the .revision on the remote server, and the changed files yields zero changes.

However, after removing the Jenkins Workspace files deploy just fine. I'm inclined this is due to Jenkins holding onto something, but I wanted to pass the question of caching across here just in case I'm missing a step.

**Comment by banago** [comment]
@JayWood I'm not sure why this happens either and I don't have experience with Jenkins. Did you figure this out since then?
