### ISSUE TITLE
Running PHPloy from SourceTree

### ISSUE THREAD

**Issue by srikat** [banago/PHPloy#326]
PHPloy works fine from the terminal. I have created a custom action in SourceTree which points to an executable shell script having:

```
#!/bin/bash

cd $REPO

echo "Pushing latest checkout to the FTP"

phploy

exit 0
```

When I run that action from within SourceTree, it shows:

> phploy.sh 
> Pushing latest checkout to the FTP
> /Users/sridharkatakam/bin/phploy.sh: line 7: phploy: command not found
> Completed successfully

Any idea?

**Comment by Eduruiz** [comment]
not sure but...
phploy command is available for your user via `/usr/local/bin`, but looks like the script doesn't have access to it (probably it's running as sudo), try running it with your user, like:
`sudo -u username phploy`

**Comment by banago** [comment]
@srikat your command assumes PHPloy is installed globally. Please make sure that's the case.
