### ISSUE TITLE
Ftp failing to connect

### ISSUE THREAD

**Issue by andrew-za** [banago/PHPloy#328]
Getting a wierd error for one of my projects using PHPLOY

Warning: ftp_rawlist(): php_connect_nonb() failed: No error (0) in D:\phploy\vendor\league\flysystem\src\Adapter\Ftp.php on line 356

PS.
Connecting via FileZilla, I need to set the transfer mode to Active - only then FileZilla connects.

**Comment by Enchufadoo** [comment]
I too had the same error when using filezilla and deploying at the same time. Meaning port 21 is busy so it can't connect.

**Comment by banago** [comment]
@andrew-za please grab latest release 4.7 - this is now fixed.
