### ISSUE TITLE
Unknown git-diff status: T

### ISSUE THREAD

**Issue by coatesap** [banago/PHPloy#33]
It seems PHPloy doesn't know how to handle a scenario where the type of a file has changed. This means that it blocks any further deployments with the error:

Oh Snap: Unknown git-diff status: T

An example would be to have a directory in the local repository which is removed and then replaced with file of the same name.

**Comment by banago** [comment]
@coatesap this issue is now solved. Please check https://github.com/banago/PHPloy/releases/tag/v3.0.14-beta and test it as you like. Happy deploying!
