### ISSUE TITLE
Problem while distributing large branch 

### ISSUE THREAD

**Issue by rogerbeckers** [banago/PHPloy#334]
Hi Guys,

Ik using this library for over a year daily but now i'm having an error. 
I'm getting this error while distribution a large branch (20846 files);
Oh Snap: Metadata can't be parsed from item '' , not enough parts.

Can someone help me ? 

Thanks!

**Comment by banago** [comment]
Hi @rogerbeckers, thanks for Using PHPloy.

What files is that and what name does it have. This is a new error message for me too.

**Comment by banago** [comment]
@rogerbeckers this seemed to be an issue with the underlaying library. Please grab latest version and check this out.

**Comment by rogerbeckers** [comment]
Thanks for the effort!
