### ISSUE TITLE
Error on deploy after QUOTE and DQUOTE feature

### ISSUE THREAD

**Issue by fxcosta** [banago/PHPloy#335]
Hello,

I received the following error message in today's deploys using Gitlab CI:

`Parse error: syntax error, unexpected '$values' (T_VARIABLE) in phar:///builds/company/project/phploy/src/PHPloy.php on line 360`

I noticed that this happened after this commit: 77c6e88ce1b2bba9a4eb892c7d9db505981dc16b by @banago 

A example of my phploy.ini:

```
[production]
scheme = ftp
path = /path
host = host
port = 21
branch = master
exclude[] = '.gitignore'
exclude[] = '.gitlab-ci.yml'
exclude[] = 'phploy.ini'
exclude[] = 'README.md'
exclude[] = 'vendor/*'
exclude[] = '.Idea/*'
exclude[] = '.history/*'
exclude[] = 'public/vendor/*'
exclude[] = 'node_modules/*'
```

To get around this, I'm downloading an earlier version of phploy:
```
   - apt-get install git zip unzip curl wget openssh-client -yqq
    - wget --quiet https://github.com/banago/PHPloy/archive/5658f521e6e4aef45cc495ef4173600324d27d3b.zip
    - unzip -qq 5658f521e6e4aef45cc495ef4173600324d27d3b.zip
    - mv ./PHPloy-5658f521e6e4aef45cc495ef4173600324d27d3b/dist/phploy.phar phploy
```

Any idea why this is happening? I could not understand. Thanks!

**Comment by banago** [comment]
@fxcosta sorry about this. Please try grabbing latest version I just pushed. Let me know if this happens again.
