### ISSUE TITLE
Getting asked for password after upgrading 4.6.3 to 4.8 (using quickmode)

### ISSUE THREAD

**Issue by SimonEast** [banago/PHPloy#336]
After upgrading from PHPloy 4.6.3 to 4.8 it now asks me for a password, even though I have the password specified in `phploy.ini` using quickmode.

I haven't had time to investigate the possible cause, so I rolled back versions for the time being. Not sure if anyone else has come across this?

**Comment by banago** [comment]
@SimonEast seems `parse_url()` breaks if you have a `#` in your password. Is that true in your case?

**Comment by banago** [comment]
More on encoding usernames and passwords: https://app.zencoder.com/docs/guides/getting-started/special-characters-in-usernames-and-passwords

**Comment by SimonEast** [comment]
No, I don't see any hashes or special characters in any of my passwords. They're just alphanumeric.

I've got a hectic week ahead so probably won't get time to troubleshoot yet, but I can post back when I eventually do.
