### ISSUE TITLE
Deployment extremely slow on 1 particular repo - could submodules be causing this?

### ISSUE THREAD

**Issue by SimonEast** [banago/PHPloy#339]
Most of my projects deploy quite fast but one particular one is excruciatingly slow. When I run the `phploy` command it hangs on this screen for 1-5 minutes before listing the files or running the deployment.

![screenshot - 01-mar-18 11_39_12 am](https://user-images.githubusercontent.com/813734/36821165-b8755f62-1d45-11e8-87a8-018dd4bae9e7.png)

Could it be because this repository has about 10 submodules? I thought they were ignored by default, but could they be causing delays?

Using phploy v4.6.3

**Comment by marcus-at-localhorst** [comment]
I experienced the same, that with submodules in the repo I waited for up to 5 minutes till the upload started. Today I used Procmon https://docs.microsoft.com/en-us/sysinternals/downloads/procmon to see what's going on and I noticed a lot of rights(?) related issues with git.exe.

I then set this particular git.exe as "Run as Administrator" and it's much faster now. Maybe someone can confirm that.
