### ISSUE TITLE
Add commit hashes to output

### ISSUE THREAD

**Issue by helmut** [banago/PHPloy#34]
It would be great if the output in the CLI would display the commit hashes that the files are being deployed from/to. Sometimes when you deploy and you have multiple commits in between and you want to rollback quickly, it can take a while to find which commit to rollback to. If you could just look in the CLI history to see what you just deployed that would be great. 

Also a command to retrieve the current commit hash that is on the server would be great too.

**Comment by banago** [comment]
I don't see this happening soon, since I like the output being very neat and clean, so I'm closing this. If someone would like to implement this, just open the issue again and send a pull request.
