### ISSUE TITLE
CYGWIN Incompatible on branch switching

### ISSUE THREAD

**Issue by ahsankhatri** [banago/PHPloy#341]
I've defined branches in multiple profiles. Before version **4.8.3** it was working as expected after upgrading to version **4.8.3** its giving an error while switching to branch.

`fatal: Invalid path '/cygdrive/c/xampp/htdocs/project/C:\xampp\htdocs\project': No such file or directory`

**Comment by banago** [comment]
@ahsankhatri is this fixed on the new version. I was not able to look into this. Please let me know.
