### ISSUE TITLE
Constant already defined

### ISSUE THREAD

**Issue by ogrosko** [banago/PHPloy#342]
Hi 
With the latest version of PHPloy v4.8.3 i'm getting PHP notices:

`PHP Notice:  Constant QUOTE already defined in /.composer/vendor/banago/phploy/src/PHPloy.php on line 409
`
`PHP Notice:  Constant DQUOTE already defined in /.composer/vendor/banago/phploy/src/PHPloy.php on line 410
`

**Comment by supernrm** [comment]
Same here,

`PHP Notice:  Constant QUOTE already defined in /.composer/vendor/banago/phploy/src/PHPloy.php on line 409

Notice: Constant QUOTE already defined in /.composer/vendor/banago/phploy/src/PHPloy.php on line 409

PHP Notice:  Constant DQUOTE already defined in /.composer/vendor/banago/phploy/src/PHPloy.php on line 410

Notice: Constant DQUOTE already defined in /.composer/vendor/banago/phploy/src/PHPloy.php on line 410`

**Comment by banago** [comment]
Just fixed. Please grab latest version.
