### ISSUE TITLE
notices - quote and dquote

### ISSUE THREAD

**Issue by helder1983** [banago/PHPloy#344]
hi, i'm having these notices when using phploy (but the deploying works fine)

Notice: Constant QUOTE already defined in vendor\banago\phploy\src\PHPloy.php on line 409

Notice: Constant DQUOTE already defined in vendor\banago\phploy\src\PHPloy.php on line 410

**Comment by helder1983** [comment]
actually, the problem happens when in php.ini error_reporting = E_ALL

**Comment by banago** [comment]
It happens because the function where the constants are defined runs multiple times. A fix is coming shortly.
