### ISSUE TITLE
Not works within linux

### ISSUE THREAD

**Issue by tomasr1981** [banago/PHPloy#350]
Hi, is it great tool, but it works just in windows (win7) form me. On Linux mint it (write phploy to terminal and launch) do not nothing without no errors.

**Comment by banago** [comment]
You need to install it first.

**Comment by tomasr1981** [comment]
I had it, but I reinstall composer and phploy and I move. I thing that manual is little bit confusing. When I install globally by composer global require "banago/phploy" calling phploy from terminal do not works, because phploy is installed on /home/username/.composer, but command extract error that phploy is not in path /usr/local/vendor.

So I tried out phar version and it is little bit better. I moved vendor to /usr/local/ and looks like much better, is there still some errors with ssh.
PHP Fatal error:  Uncaught Error: Call to undefined function phpseclib\Crypt\xml_parser_create() in /usr/local/vendor/phpseclib/phpseclib/phpseclib/Crypt/RSA.php:1330
Stack trace:
#0 /usr/local/vendor/phpseclib/phpseclib/phpseclib/Crypt/RSA.php(1569): phpseclib\Crypt\RSA->_parseKey('PuTTY-User-Key-...', 2)
#1 /usr/local/vendor/league/flysystem-sftp/src/SftpAdapter.php(272): phpseclib\Crypt\RSA->loadKey('PuTTY-User-Key-...')
#2 /usr/local/vendor/league/flysystem-sftp/src/SftpAdapter.php(249): League\Flysystem\Sftp\SftpAdapter->getPrivateKey()
#3 /usr/local/vendor/league/flysystem-sftp/src/SftpAdapter.php(197): League\Flysystem\Sftp\SftpAdapter->getAuthentication()
#4 /usr/local/vendor/league/flysystem-sftp/src/SftpAdapter.php(178): League\Flysystem\Sftp\SftpAdapter->login()
#5 /usr/local/vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php(578): League\Flysystem\Sftp\SftpAdapter->connect()
#6 /usr/local/vendor/league/flysystem-sftp/src/SftpAdapter.php(497): League\Flysystem\Adapter\AbstractFtpAdapter->getConnection()
#7 / in /usr/local/vendor/phpseclib/phpseclib/phpseclib/Crypt/RSA.php on line 1330

**Comment by banago** [comment]
> Send greetings to Albania :)

Thanks, @tomasr1981 

Please pull the latest version. This should be fixed now.
