### ISSUE TITLE
Different folder for git repoository and ftp server

### ISSUE THREAD

**Issue by aps90** [banago/PHPloy#351]
Hi, I have a problem to deploy in different folders, my git repository and the ftp server to deploy. This is the context and how I try to solve:

GIT Repository: 
**src/wp-content/themes/file.txt**

FTP Server:
**/home/wp-content/themes/file.txt**

In the deploy PHPLoy create a src folder in /home directory:

**/home/src/wp-content/themes/file.txt**    bad

My solution was to add:

base = 'src'  but this doesn't work. 

thank you for your help.

**Comment by banago** [comment]
@aps90 `base` is back to normal now. Please grab the latest version.
