### ISSUE TITLE
Build an official Docker image

### ISSUE THREAD

**Issue by spawnia** [banago/PHPloy#352]
Hey,

would you be up for packaging PHPloy as a Docker image?
It would enable more flexible use in CI pipelines.

I can provide a Dockerfile if you are up for it.

**Comment by lekkerduidelijk** [comment]
I've been using my own for 2 years now: https://hub.docker.com/r/lekkerduidelijk/phploy/
I use it in a GitLab CI pipeline on a daily routine.

**Comment by spawnia** [comment]
This one looks fine, maybe up the alpine version and it should be fine https://github.com/lekkerduidelijk/docker-phploy/blob/master/Dockerfile

**Comment by banago** [comment]
Guys, we finally have an official Docker image.
