### ISSUE TITLE
Confuse about environment variables 

### ISSUE THREAD

**Issue by ghost** [banago/PHPloy#355]
Hi
I read the doc and can't resolve my problem. I don't want to store user + password in the phploy.ini. I try to make a call command like :

`PHPLOY_USER=“myuserhere" PHPLOY_PASS=“mypasshere" php phploy -s staging`

But is not working, because both variables look empty PHPLOY_USER + PHPLOY_PASS

Someone can share a sample please ?

**Comment by steevesf** [comment]
Hmm no sign of life ...

**Comment by banago** [comment]
Very busy. Will get to this soon.

**Comment by banago** [comment]
That is not how you set environment variables.
