### ISSUE TITLE
Phar is not working anymore

### ISSUE THREAD

**Issue by plashenkov** [banago/PHPloy#357]
Hi!
I'm trying to build a Phar and it produces non-working Phar.
```
chmod +x ./build
./build
```
Generates Phar successfully, but when we try to run it, we get:
```
PHP Warning:  require(phar://[...]/phploy.phar/vendor/composer/../symfony/polyfill-ctype/bootstrap.php): failed to open stream: phar error: "vendor/symfony/polyfill-ctype/bootstrap.php" is not a file in phar "[...]/phploy.phar" in phar://[...]/phploy.phar/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  require(): Failed opening required 'phar://[...]/phploy.phar/vendor/composer/../symfony/polyfill-ctype/bootstrap.php' (include_path='phar://[...]/phploy.phar:.:/usr/share/php') in phar://[...]/phploy.phar/vendor/composer/autoload_real.php on line 66
```
The issue with this line, I suppose:
https://github.com/banago/PHPloy/blob/master/build#L30
You include here only some folders from vendor manually. But what if they require another dependencies? In our case one of our direct dependencies requires `/symfony/polyfill-ctype`. And as a result we get a non-working Phar.

Let's think what we can do here.
1. Maybe the `./build` script should copy all necessary PHPloy files to a temporary folder (without vendors folder), then shell_exec `composer --no-dev install` there and then build the Phar packed with complete vendors folder (as it is)?
2. We can still add `--no-dev` to this command: https://github.com/banago/PHPloy/blob/master/build#L14
Then, if you are a developer, if you need to build a Phar, you just delete vendors dir and run `./build`, and you get a clean Phar. Then if you need your dev-dependencies again (phpunit, etc.), you delete vendors dir again and run `composer install`. If you are not a developer and just downloaded ZIP to build a Phar, you just run `./build` and that's all.

Anyway, maintaining dependencies manually (as you do here: https://github.com/banago/PHPloy/blob/master/build#L30) is the wrong way, I believe. We should simply include the vendors folder as it is.

**Comment by plashenkov** [comment]
The Phar is still an important way of distribution. `composer global require` sometimes gives conflicting dependencies error, when packages you are about to install globally require one lib, but different versions. Phars are self-contained and this is why they win in this situation.

**Comment by banago** [comment]
This is now fixed. Please pull the latest version.
