### ISSUE TITLE
Mac: Fatal error: require(): Failed opening required

### ISSUE THREAD

**Issue by MartineJacobsen** [banago/PHPloy#358]
Forgive me in advanced – I am very new to these kinds of installations. But I can't seem to get the installation right.

I have installed phploy globally via composer.

When testing if it is installed I get this:

```
$ phploy

Warning: require(/usr/local/bin/../vendor/autoload.php): failed to open stream: No such file or directory in /usr/local/bin/phploy on line 7

Fatal error: require(): Failed opening required '/usr/local/bin/../vendor/autoload.php' (include_path='.:') in /usr/local/bin/phploy on line 7
```

Paths of my files:
```
phploy: /usr/local/bin/phploy
composer: $HOME/.composer/
```

This is my .bash_profile:
```
export PS1="⚓ "
export NVM_DIR="$HOME/.nvm"
[[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh  # This loads NVM
export PATH="$PATH:$HOME/.composer/vendor/bin"
```

This is my $PATH:
```
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/username/.composer/vendor/bin:/Users/username/.composer/vendor/bin
```

If anyone would be kind enough to help this newbie, I would be so happy! Maybe it helps other newbies out there :)

**Comment by banago** [comment]
@MartineJacobsen there was an issue with the paths of PHPloy of that version. Please grab the latest version.
