### ISSUE TITLE
ssl not working

### ISSUE THREAD

**Issue by wei2go** [banago/PHPloy#359]
First of all, not sure why the dist folder with phploy.phar is not included in the latest two releases (4.8.4 and 4.8.5)?

I use phploy on windows, it's been working fine, until my hosting provider update their security settings. In FileZilla it can be connected using 'explicit FTP over TLS'. Now I'm trying to find similar settings in phploy. I've been reading another thread, seems like 'ssl = true' is the way to go? However, when I try it, it gives me the following errors:

`Fatal error: Call to undefined function League\Flysystem\Adapter\ftp_ssl_connect() in phar://C:/phploy/dist/phploy.phar/vendor/league/flysystem/src/Adapter/Ftp.php on line 131`

phploy version: 4.8.3

**Comment by banago** [comment]
Hey, @wei2go please grab the latest version. This is now fixed.
