### ISSUE TITLE
"Oh Snap: Unknown git-diff status" when diff shows warnings

### ISSUE THREAD

**Issue by SimonEast** [banago/PHPloy#361]
When running `phploy -s staging --debug`, I get a long list of files, which ends with...

```
M       wp-load.php
M       wp-login.php
M       wp-settings.php
M       wp-signup.php
M       wp-trackback.php
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your diff.renameLimit variable to at least 2118 and retry the command.

Oh Snap: Unknown git-diff status. Use '--sync' to update remote revision or use '--debug' to see what's wrong.
```

Is it possible that the warnings shown at the end here are breaking phploy and stopping it from deploying?

**Comment by SimonEast** [comment]
The workaround I found is to run this command:

    git config diff.renameLimit 999999

But I wonder if it should be possible for phploy to ignore the warnings and deploy anyway?

**Comment by banago** [comment]
@SimonEast can you dig into this yourself. I don't see how I can reproduce the error.

**Comment by banago** [comment]
@SimonEast in that case the deployment could not go ahead because the diff was not in place. You had to do that git config update.
