### ISSUE TITLE
A posibility to deploy a specific folder from the repository

### ISSUE THREAD

**Issue by danielzzz** [banago/PHPloy#384]
this is related to #224 but I think it's not the same.

In my project I have a dist directory (which is also stored in git)

I would like to deploy only the CONTENT (diff)  of the dist directory (not the directory itself).

this is because I have a limited ftp access which points directly to the dist directory on the server.

is it possible?

thanks, kind regards
dan

**Comment by banago** [comment]
I think we have support for that. Add this to your phploy.ini:

> base = 'dist/'

Let me know how it goes.

**Comment by banago** [comment]
Seems there is an issue with the `base` option. Let's continue the discussion on #373
