### ISSUE TITLE
Update required PHP version

### ISSUE THREAD

**Issue by lhsazevedo** [banago/PHPloy#386]
Readme says PHP 7.0+ but composer.json requires PHP 7.3+

**Comment by menturion** [comment]
+1 
Same here. 

PHPloy needs to be updated to be compatible with higher PHP versions (e.g. 7.4) which requires a shift to support Flysystem v2, reported here https://github.com/banago/PHPloy/issues/385

**Comment by lhsazevedo** [comment]
Doesn't Flysystem v1 supports PHP 7.2.5+ and PHP 8.0?

https://github.com/thephpleague/flysystem/blob/1.x/composer.json
```
"require": {
    "php": "^7.2.5 || ^8.0",
    "ext-fileinfo": "*",
    "league/mime-type-detection": "^1.3"
},
```

Did you experience any problems with PHPloy on PHP 7.4?

**Comment by menturion** [comment]
Sure. 

Did you test your script with PHP 7.4?

`composer.json` excerpt:
```
{
   "config":{
        "platform": {
            "php": "7.4"
        },
    },
    
    ...
}
```

**Comment by lhsazevedo** [comment]
Hmm, this just tells Composer to ignore the current PHP version and install dependencies as if you were running PHP 7.4.

To see which PHP version you're actually running you can try `php -v` on your terminal.

I will test PHPloy on 7.4 later today to see if I can reproduce your issue.

**Comment by lhsazevedo** [comment]
@menturion I just tested the latest build from "dist" directory, on PHP 7.4, and it worked perfectly.

**Comment by menturion** [comment]
Thanks.
I'm running v7.4. This forces Flysystem to be updated to v2 which results into the mentioned problems. So that changes have to be made in your script according to https://flysystem.thephpleague.com/v2/docs/advanced/upgrade-to-2.0.0/

**Comment by lhsazevedo** [comment]
...

**Comment by mathmul** [comment]
Does it work with PHP 8.0.x ? I installed it globally as per instructions, but dependency  `League\Flysystem\Adapter\FTP` seems to be missing. Can someone else test it locally?

**Comment by menturion** [comment]
@mathmul 

It doesn't work, see the issue report here https://github.com/banago/PHPloy/issues/385.
As long as this issue isn't fixed I recommend to create a separate vendor lib folder for PHPloy with `composer.json` ...

```
        "platform": {
            "php": "7.3"
        },
        "platform-check": false
```

**Comment by NicolasRoehm** [comment]
Same here! Still no chance for a Flysystem v2 implementation?

**Comment by lhsazevedo** [comment]
Please open a new issue for the Flysystem upgrade.
