### ISSUE TITLE
PHPloy v3

### ISSUE THREAD

**Issue by banago** [banago/PHPloy#43]
Hi guys,

I have some exciting news to share. I took a good chunk of time to add a feature that I was needing a lot lately and that is sFTP support: https://github.com/banago/PHPloy/tree/feature/secure

To do that, I made use of this great library here: https://github.com/tangervu/Connection.php (1) which I ended up forking to make several improvements to play well with PHPloy and to make it a composer package. You can fine it here: https://github.com/banago/Bridge

This means PHPloy will be a Phar in the future, much like composer. To load depencencies, (only Brige for now) please run `composer install`. To build the phar, all you need to do is run: `php build`. 

Things seem to work fine, expect the fact that the phar won't work globally on my laptop. It only works locally. A lot of testing is needed. And a lot of further work and fine-tuning too.

@fadion can you help with overall architecture of PHPloy package. Perhaps bring some work from Maneuver over and then you can just drop PHPloy as a dependency on Maneuver. I know you are the right guy for this. :smile_cat: 

@SimonEast your Windows testing and development is indispensable :+1: 

@JayBizzle could you please add those improvements you added to master branch to feature/secure branch too. That would be awesome.

@oxodesign, @reinink,  @rupaheizu and everybody else your contributions are more then welcome and very appreciated.

Thanks everyone.

 (1) Connection.php is now a composer package too. Was updated after this was posted.

**Comment by banago** [comment]
Hey @fadion, @SimonEast and @JayBizzle, do you guys thing we should merge `feature/secure` to master and make it the default version now. Seems pretty stable to me these days. Please let me know.

**Comment by JayBizzle** [comment]
Its been out in the wild for a while now with no real serious issues reported. I think getting it merged will clean up the code base, then we can look at pushing onwards with new stuff.

**Comment by banago** [comment]
I feel the same. Let's hear from the rest of the team.

**Comment by SimonEast** [comment]
Sorry guys, I've been pretty flat-out recently so haven't kept up-to-date with developments.  If you see my earlier post in this thread (back in August), I had a few suggestions including an issue where on Windows you'd get odd and confusing error messages when attempting to use SFTP.  Was hoping to look into that more when I got time (but haven't had a chance).  Do you know if those items got looked at?

**Comment by fadion** [comment]
I'm for it too!

**Comment by banago** [comment]
PHPloy v3 just hit beta. PHPloy v2 is now on legacy branch. Happy deploying everyone. Thanks for using and contributing to PHPloy.

Check it out: https://github.com/banago/PHPloy

**Comment by banago** [comment]
PHPloy v3 is finally stable. Thanks everyone for your feedback and contributions. Support for purging directories is now added to PHPloy.

Check the stable version out: https://github.com/banago/PHPloy
