### ISSUE TITLE
Issues with rollback command

### ISSUE THREAD

**Issue by SimonEast** [banago/PHPloy#50]
There's currently two issues with the `--rollback` command.
1. It doesn't handle submodules correctly.  [See source code note here.](https://github.com/banago/PHPloy/blob/dffa97ee72741c9eb278470333e5d3dbb6277910/src/PHPloy.php#L679)
2. It returns the working copy to the master branch, which may not be what the user intended. [See source code note here.](https://github.com/banago/PHPloy/blob/dffa97ee72741c9eb278470333e5d3dbb6277910/src/PHPloy.php#L778)

I'm unlikely to have time to fix these any time soon unfortunately, but if anyone else wants to have a go, feel free. :+1:

**Comment by banago** [comment]
@SimonEast this issue of returning to master after rollback is now fixed by this super-awesome contrbutor @GuidoHendriks.

For the submodule handle, I don't see how it can be implemented - I'm out of ideas. What's on your mind?

**Comment by banago** [comment]
Submodule rollback won't work at this time.
