### ISSUE TITLE
Pre/Post deployment commands

### ISSUE THREAD

**Issue by JayBizzle** [banago/PHPloy#51]
Just noting this down as a discussion point for a possible future feature.

My current deployment workflow, using dploy.io, allows me to run shell commands on my server after the deployment has complete. I usually have a minimum of `composer install` getting executed after my deployments. It would be nice for PHPloy to have such a feature.

Thoughts?

**Comment by banago** [comment]
@JayBizzle is this even possible to do through ftp/sftp? I think we will need to add support for ssh to do that. Right?

**Comment by JayBizzle** [comment]
SFTP is over SSH isn't it?

http://en.wikipedia.org/wiki/File_Transfer_Protocol#SFTP

**Comment by banago** [comment]
Yeah, but it comes with it's own set of commands. You cannot run `composer
install` from sftp as far as I know.

**Comment by JayBizzle** [comment]
I use http://dploy.io for some of my projects, and with that, i just setup an SFTP connect and tell it to run commands after deployment, including `composer` stuff so i presume it is possible :confused:

**Comment by banago** [comment]
I hope we can do it too. :smile:

**Comment by StyxOfDynamite** [comment]
Would be great if we could give the name of a script to be run after deployment.

Example use-cases.

* database migrations
* tests
* server configuration changes
* restart services
* updating remote dependencies

I'm deploying to several environments in the following order.

dev - private local development instance
test - private remote test server 
qa - limited access server where work can be tested by client  
live - clients current public site

at least for the first 3 I'd be happy to automate post-deployment steps, things like updating composer, restarting nginx or apache, running database migrations, adding .conf block for new features that run on a dedicated subdomain.

I know there are alternatives to PHPloy but for most of the projects I work on the client(s) aren't interested in the financial overheads attached to CI for the development side of things.

If we could add a single or multiple scripts to the repo and have PHPloy trigger them in order it would make things that little bit more awesome.

**Comment by InfinityWebMe** [comment]
:+1:  databases migrations and updating remote dependencies, it would be great :D

**Comment by inluxc** [comment]
Here is an discussion about that, i run magento projects and i would love this feature in the deploy action.
http://unix.stackexchange.com/questions/55190/how-to-send-multiple-commands-to-sftp-using-one-line

**Comment by banago** [comment]
:+1:

**Comment by banago** [comment]
Support for hooks is now added in version 4.0 that landed in master branch a bit ago. Please check it out.
