### ISSUE TITLE
Problem with the new version (feature to SFTP

### ISSUE THREAD

**Issue by rodrigoiohb** [banago/PHPloy#53]
I am trying to connect to an SFTP Server.. 

PHP Fatal error:  Call to a member function exists() on a non-object in phar:///var/www/mysite/phploy.phar/src/PHPloy.php on line 480
PHP Stack trace:
PHP   1. {main}() /var/www/mysite/phploy.phar:0
PHP   2. include() /var/www/mysite/phploy.phar:10
PHP   3. Banago\PHPloy\PHPloy->__construct() phar:///var/www/mysite/phploy.phar/phploy.php:11
PHP   4. Banago\PHPloy\PHPloy->deploy() phar:///var/www/mysite/phploy.phar/src/PHPloy.php:221
PHP   5. Banago\PHPloy\PHPloy->compare() phar:///var/www/mysite/phploy.phar/src/PHPloy.php:563

**Comment by emilsgulbis** [comment]
When I'm trying to phploy, terminal just says Could not connect to 'my.domain.com' and nothing more.
```
[staging]
    scheme = sftp
    user = username
    pass = password
    host = my.domain.com
    path = /public_html/
    port = 22
    passive = true
```

and quickmode fails too.

https://github.com/fadion/Maneuver for laravel works, but this for (non-laravel) doesn't.

**Comment by nolfranklin** [comment]
Think I might be in the same boat as @emilsgulbis.

**Comment by banago** [comment]
@fadion's fix should fix PHPloy too, but I've not updated it yet. Will do very soon. Thanks for the head-ups.

**Comment by banago** [comment]
Hi everyone,

This annoying bug is now fixed. Thanks everyone for your patience. Please grab the latest build from `bin/`folder and put it in your `usr/local/bin` or in your project directory and you will be good to go.

Happy deploying! :smiley_cat:
