### ISSUE TITLE
How to upload files which are ignored by git 

### ISSUE THREAD

**Issue by hyyan** [banago/PHPloy#55]

**Comment by julio6114** [comment]
Always not available ?

**Comment by nikolaykovenko** [comment]
@julio6114 Here is pull request with this feature https://github.com/banago/PHPloy/pull/68. I hope it will be merged soon, but you can use @saibotd fork, if you want.

**Comment by julio6114** [comment]
Oh thanks!
I just noticed that my problem is another! :)
In fact, I want to exclude files which are not in .gitignore.
For example I've a Gruntfile.js which is versionned but I don't upload it on staging.
Do I created an other issue ?
