### ISSUE TITLE
Revision file incorrect if committing during deployment

### ISSUE THREAD

**Issue by hellodaniel** [banago/PHPloy#56]
I might be incorrect but I've noticed this a few times -- 

If I'm doing a long deployment, say an initial deployment of many thousands of files, then make commits during that deployment the .revision file on the server is incorrectly updated to the latest local revision. i.e.: the revision when deployment completed, not when it was started. 

When detected I just sync the server to the correct revision; however sometimes this is not picked up and files are missing or outdated on the server as a result. 

How to re-produce: Make a local commit whilst phploy is deploying.

**Comment by banago** [comment]
Hey @hellodaniel and @SimonEast, this issue is now fixed. Happy deploying!
