### ISSUE TITLE
Windows Issues

### ISSUE THREAD

**Issue by ajtroxell** [banago/PHPloy#57]
Following installation instructions word for word, yet running phploy within project prompts that phploy is not a recognized command. This is after adding php.exe and path to phploy to environment variables.

It does work if I place phploy and phploy.bat in my project folder, but it would be nice to not have to do this with each project, as that is what the installation instructions indicate by using it globally.

**Comment by banago** [comment]
@ajtroxell did you find a solution to this issue?
