### ISSUE TITLE
Deploying to all servers should require a --all parameter

### ISSUE THREAD

**Issue by gullij** [banago/PHPloy#63]
The default behaviour of uploading to all servers could cause problems if people use the setup for different environments as the example deploy.ini shows. It's highly unlikely people would want to deploy to development, staging and production environments all at the same time. A --all parameter or something similar seems more logical than defaulting to deploying everywhere.

**Comment by JayBizzle** [comment]
:+1:

**Comment by banago** [comment]
@gullij thinking about this I came the the conclusion that we have a solution in place for this. It's the other way around of what you suggest but works the same none the less. So, if you want to deploy one to one of your environments, you specify that environment with the `-s` or the longer `--server` parameter, like this:

    phploy -s staging

Or:

    phploy --server staging

This works great and I use it almost daily on websites where I have more then one environment specified. This, I'm closing this and wish you good luck and happy deploying.

**Comment by banago** [comment]
Hi @gullij and @JayBizzle.

Due to another developer proposing this feature, this is now added to PHPloy. The guy proposing it, implemented it too, so everyone is happy. :smile_cat: 

Happy deployment!
