### ISSUE TITLE
PHPloy in window 64 bit

### ISSUE THREAD

**Issue by kodeplusdev** [banago/PHPloy#64]
I run on my computer window 7 64bit and get this error. Please help me to fixe them. Thanks.

![test](https://cloud.githubusercontent.com/assets/7855608/5449218/c8e5f482-8523-11e4-9561-5d6476d4740d.png)

**Comment by banago** [comment]
@kodeplusdev, I suggest you switch to version 3. Even though it's tagged as alpha is very stable and works great. I'm closing this issue. Good luck and happy deploying!
