### ISSUE TITLE
Test Suite

### ISSUE THREAD

**Issue by JayBizzle** [banago/PHPloy#69]
I had some time the other day to get back involved in writing some more updates but then I remembered what a pain it was to do any kind of testing the last time I contributed.

I just wondered how you or any other contributors test their contributions, and have you thought about putting some kind of test suite together to facilitate automated testing? Im no expert in this field, but it is something most projects have these days, and definitely something i'd like to get involved with to further my own knowledge in this area.

**Comment by banago** [comment]
I'm not very much  into Unit Testing either and I'm looking forward to it. So, let's make this a feature to add. Right now I test by running commands on real project on the scenarios I want to test. Thanks @JayBizzle

**Comment by fadion** [comment]
Mocking the git commands and server deployment features would basically render the Unit Tests useless. I believe it would benefit a lot more from acceptance tests by setting up a test git repo and server. I may help in the future.

**Comment by banago** [comment]
@fadion I know you can help here and I'm hardly waiting the the day. :smiley_cat:

**Comment by mbrugger** [comment]
I am currently looking into creating integration tests for PHPloy. 
Using docker I run a local sftp server sharing a directory as upload target. After executing PHPloy with a local repository I can simply diff the repository and the shared volume. 
At the moment I am still testing manually with shell scripts but I am looking into test frameworks right now. I personally like JUnit, maybe in combination with gradle/groovy.
Is there a set of test cases you would like to see implemented first?
Any objections against the technologies I plan to use?

**Comment by banago** [comment]
@mbrugger thanks very much for looking into this. It has been hanging around forever. 

While I don't use Java at all my self, I cannot force you to use another set of technologies, since I just love to see some testing implementing for PHPloy. In this case, the right tools are the ones used. :smile: That said, if we could keep it all PHP and bash, that would be awesome.

Here is a short list coming to my mind:
 * Upload and delete files
 * Upload and delete submodules files
 * Purge files

That would be a start. We can build anything over those.

**Comment by mbrugger** [comment]
Ok, I will see what I can do using PHP.

[PHPUnit](https://phpunit.de), [docker-php](https://github.com/docker-php/docker-php) for controlling the sftp server and [Git Streamwrapper for PHP](https://github.com/teqneers/PHP-Stream-Wrapper-for-Git) should do the job as well.

**Comment by banago** [comment]
@mbrugger that is just perfect. :100:

**Comment by mbrugger** [comment]
I still don't like PHP ;-) but a first test is available verifying that the git repository is synchronised with the sftp directory. (branch test in my fork)

- 1. install [docker](https://docs.docker.com/engine/installation/)
- 2. start the test server
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant/PHPloy$ ./tests/start_test_server.sh
```
- 3. run the tests
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant/PHPloy$ vendor/bin/phpunit tests
PHPUnit 4.8.26 by Sebastian Bergmann and contributors.
...
Time: 2.32 seconds, Memory: 4.25MB
OK (3 tests, 4 assertions)
vagrant@vagrant-ubuntu-trusty-64:/vagrant/PHPloy$ 
```
- 4. stop the sftp server
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant/PHPloy$ ./tests/stop_test_server.sh 
```

Will cleanup the code tomorrow

**Comment by banago** [comment]
@mbrugger PHP is not very pretty, thanks for your effort here. It's great you have it ready. Cannot wait to check it out. Keep it up.

**Comment by banago** [comment]
@mbrugger I can see you are on an earlier version of PHPloy. Could you please pull from master?

**Comment by mbrugger** [comment]
I pulled the latest changes and also I activated [travis](https://travis-ci.org/mbrugger/PHPloy) for automated test execution
![Travis CI Status](https://travis-ci.org/mbrugger/PHPloy.svg?branch=tests)

Now it is time to give the tests a better structure and increase the number of tests.

**Comment by mbrugger** [comment]
@banago before i continue writing additional tests/improve the test system.
Is the way the test system is currently set up something you would like to add to the project?

I just read #257 and think this is something that could easily be covered by a test case.

**Comment by mbrugger** [comment]
Refactored the tests a little, a shared base class to inherit from is no longer needed (which is a nightmare as soon as test sets grow), created parametrised tests to verify sftp and ftp sync with a single test case

**Comment by banago** [comment]
@mbrugger thank you very much for implementing testing. This is the best thing to happen to PHPloy for a long time. 

I added the initial testing docs to `contributing.md`. Do you think you can elaborate on them a little bit more, is everyone can get started easily. Thanks so much.

**Comment by mbrugger** [comment]
I will be on vacation the next 2 weeks but I will be happy to add test instructions on my return

**Comment by banago** [comment]
@mbrugger have a great vacation. This can wait. :+1:
