### ISSUE TITLE
Change file name on deployment

### ISSUE THREAD

**Issue by decanus** [banago/PHPloy#71]
A way to change file names.
Ex.

system.ini // Dont deploy
system.live.ini => system.ini // Change name for live server

**Comment by banago** [comment]
Personally, I don't think I would spend time on that, and I expect the same from the rest of the devs since there are other features that are hanging there for about one year. If you would like to contribute that code, I'd be more than happy to include it. All the best.

**Comment by decanus** [comment]
@banago Shall I just create a PR once I'm done?

**Comment by banago** [comment]
Yes, directly to master would do right now. Thanks very much @decanus

**Comment by decanus** [comment]
https://github.com/banago/PHPloy/pull/72

**Comment by banago** [comment]
@decanus thanks very much for your contribution. Before I pull it in, I need you to test it well, since this is going straight to master branch. And, the other thing is, once you make 3 contributions, you qualify as an author, so stick around. ;)

**Comment by decanus** [comment]
Ah that's cool, maybe I'll get started on the web UI. If it doesn't work 100% tell me and I'll look over it.

**Comment by banago** [comment]
@decanus I checked the implementation again. What happens if you want to rename more then one file?

**Comment by decanus** [comment]
As long as the indexes match it should work

**Comment by banago** [comment]
How do indexes work - you couple them together? Is this mentioned in readme.md?

**Comment by decanus** [comment]
yeah, [0] in remote is related to [0] in local

**Comment by decanus** [comment]
Have not put it in readme

**Comment by JayBizzle** [comment]
With all these extra options in the `ini` file, wouldn't it be advantageous to have a more advanced ini parser?

Something like https://github.com/austinhyde/IniParser

**Comment by decanus** [comment]
I feel as though the ini could be replaced with a json file

**Comment by JayBizzle** [comment]
@decanus yes, that is also not a bad idea

**Comment by decanus** [comment]
@banago or @JayBizzle could one of you test my code? I currently dont have the necessary resources

**Comment by banago** [comment]
@decanus do you think you can put a little bit of more effort into this? The feature needs to be added to readme.md so other will know about it. And testing it with multiple files would be great. This feature is your little baby so it needs your love. :smile:

**Comment by decanus** [comment]
Sure, I'll try so an extensive test this weekend

**Comment by banago** [comment]
@decanus did you find time to look into this. :)

**Comment by decanus** [comment]
@banago I have been busy, ill look into it next week when I am off from Work

**Comment by banago** [comment]
:+1:

**Comment by banago** [comment]
@decanus I'm closing this for now. Please reopen it anytime you think you are ready to work on this. Looking forward to your contribution.
