### ISSUE TITLE
Change deploy.ini to deploy.json

### ISSUE THREAD

**Issue by decanus** [banago/PHPloy#74]

**Comment by banago** [comment]
@decanus why do you feel inclined we should do that?

**Comment by decanus** [comment]
Multi dimensional arrays for settings @JayBizzle agrees that it could be a good idea.

**Comment by banago** [comment]
I like the idea of a supporting a `json` configuration file alongside `ini` file. However, the reasons as of now is not to support multi-dimentional arrays since we don't need them anywhere.
