### ISSUE TITLE
Travis-CI for builds

### ISSUE THREAD

**Issue by decanus** [banago/PHPloy#76]
This would help get build statuses and would automatically build the .phar file

**Comment by banago** [comment]
That would be great. :smile:

**Comment by decanus** [comment]
It's pretty simple too, and automates a lot

**Comment by banago** [comment]
I tried it some times ago and the system seemed buggy - I kept seeing some
Symphony errors, so I just dumped it. Happy to get to it again though.

You have the lead here.

**Comment by JayBizzle** [comment]
+1

**Comment by decanus** [comment]
I can't do any of the travis stuff as I am not repo owner. I could guide you through it though if you do the basic setup like linking the repo and github

**Comment by decanus** [comment]
http://docs.travis-ci.com/user/getting-started/

**Comment by banago** [comment]
For the near future we will continue to manually build `phar` archives. We might revisit Travis-CI later.

**Comment by martin-sucha** [comment]
@banago I'd be interested in more details about the reason why. Also it might be useful to use Travis CI for checking the code style even if it won't get used to build the phar archives.

**Comment by JayBizzle** [comment]
StyleCI should be used for code style.

Travis should be used for testing, but probably not until the code has been refactored for easier unit testing in perhaps v4.0 of PHPloy

**Comment by banago** [comment]
@JayBizzle yes, that's the idea. @martin-sucha we will eventually have it but I don't want to see things in the issues that I are not bugs and I cannot focus on immediately.

**Comment by martin-sucha** [comment]
@JayBizzle didn't know about StyleCI, will check it out. Thanks!
@banago thank you for the info
