### ISSUE TITLE
What if the network fails abruptly ? will the push begin from the starting.

### ISSUE THREAD

**Issue by nepsdotin** [banago/PHPloy#77]
Consider you have a really a huge bunch of files. The moment you are about to complete network broke. what will happen, will it start from the beginning or only the few files it just missed to upload.

**Comment by banago** [comment]
@nepsdotin it will start from the beginning. If you want me to explain why, just let me know. Happy you asked.

**Comment by nepsdotin** [comment]
It should continue from where it left right, that would save lot of time especially when you are pushing lot of stuffs to the server. Don't you think so

**Comment by banago** [comment]
I agree. I would be a great feature to have and it can be achieved by keeping track of what's been uploaded already and checking that on every deployment. That needs to be developed though. Would you like to contribute that feature implementation?

**Comment by banago** [comment]
@nepsdotin I'm closing this issue for now. If you would like to contribute here, please fell free to reopen it. All the best.
