### ISSUE TITLE
Hide password input

### ISSUE THREAD

**Issue by GuidoHendriks** [banago/PHPloy#82]
If there's no password in the deploy.ini, PHPloy will ask the user for the password. In some cases you might not want the password in the config file. In that case you might not have it shown in the terminal when typing it either.

Suggestion to fix this: Hide the password input.

I'd be happy to implement it if you think this would be a good addition.

**Comment by banago** [comment]
Yes, I think it will be a great addition. I thought about this when implementing the feature, but did not give much thought to it so, it's raw now. This is all yours @GuidoHendriks :+1:

**Comment by GuidoHendriks** [comment]
Fixed in #86.

**Comment by banago** [comment]
Yes, indeed. :smile_cat:
