### ISSUE TITLE
PHPloy 4

### ISSUE THREAD

**Issue by banago** [banago/PHPloy#83]
Hi everyone,

Now that PHPloy 3 is out of the door, it's time we planed new next major release, PHPloy 4. I'll try to lay out the changes and features I'd like to see to make it into the next version.

**Better OOP**
Even though PHPloy is already object-oriented, it's time take it to the next level. The best example to follow here is [Maneuver](https://github.com/fadion/Maneuver), a Laravel package by my buddy @fadion, which rewrites PHPloy and then gives it a Laravel specific flavor. That would allow of higher code quality of PHPloy and better usage by other packages, which in stead of re-implementing it, would just wrap PHPloy functionality. This would make better use of our collective efforts too.

**Drop Bridge**
[Brige](https://github.com/banago/Bridge) is our connections library and it helped us to support SFTP in PHPloy, which was a great addition. Bridge does it's job very well, but now I feel there are better alternatives out there and I've got my eyes on [Flysystem](https://github.com/thephpleague/flysystem) which is an awesome package with a wider protocol support. The greats benefit we get from this that we will drop `php_ssh2` extension as a dependency, which is a pain to install for many developers, and instead use [phpseclib](https://github.com/phpseclib/phpseclib), which comes with the library. Also, using this library will hopefully allows us to integrate also `before` and `after` hooks to run with the deployment jobs.

**Upgrade to PHP 5.4**
The other thing that I think it high time we did is upgrade to PHP 5.4. I don't think we will run into any issues with this and as developers we will have some nicer tools at hand.

In terms of current issues, I hope I'll be able to add/fix issues  #25, #50 and #51.

I would like to ask you guys to comment on the above notes and add your thoughts on what you would like to see make it in PHPloy 4. 

Let's make this happen!

**Comment by JayBizzle** [comment]
Agree with all the above, plus a better testing platform as mentioned in #69

**Comment by banago** [comment]
Everyone, PHPloy 4.0 alpha is out: https://github.com/banago/PHPloy/tree/4.0

As envisioned several months ago, Bridge is dropped in favor of Flysystem package. Also overall OOP architecture is improved.

Some non-backward compatibly changes have been introduced such as, `skip[]` is now `exclude[]` and `others` is now `include[]`. Also, all references to `deploy.ini` are now `phploy.ini`

I'd really appreciate you checking it out and contributing any improvements you see fit. Thanks a lot.

**Comment by JayBizzle** [comment]
Awesome stuff, will check it out when I get a minute

**Comment by corvannoorloos** [comment]
Hello,

Trying to deploy [all including a submodule](https://github.com/corvannoorloos/example-website) to an empty server I'm receiving this message:
```
$ phploy.bat --submodules
---------------------------------------------------
|                PHPloy v4.0-alpha                |
---------------------------------------------------
Scanning repository...
   Found 1 submodules.
   Found submodule wordpress.
      Scanning for sub-submodules...
No revision found - uploading everything...

SERVER: default
 ^ 1 of 3 README.md
 ^ 2 of 3 index.php
 ^ 3 of 3 wp-config.php


SUBMODULE: wordpress
No revision found - uploading everything...
 + Created directory 'wordpress/'.
 ! File not found - please check path: C:\apache\htdocs\example-site/wordpress/README.md
 ^ 2 of 3 wordpress/index.php
 ! File not found - please check path: C:\apache\htdocs\example-site/wordpress/wp-config.php

|----------------[ 3.74K Deployed ]----------------|
```
All of the mentioned files are in the root directory `example-site`. Not in `example-site/wordpress` (except a different `index.php`)

After the root files are correctly uploaded, an almost empty subdirectory is created. Only containing the different `index.php`.

Could someone tell why the complete submodule/directory isn't uploaded as well?

**Comment by jchristopher** [comment]
Just wanted to pass along a note that I got hung up on some public key authentication issues in version 3.x but it's not an issue here! Thanks so much for your work on this it saves a lot of headache!

**Comment by banago** [comment]
Hello everyone,

PHPloy 4.0 has hit the master branch. It's in beta, but should be rock solid. 

Grab a copy and happy deployment!

:fireworks:

**Comment by baoweber** [comment]
So far great! I will keep on testing, but the pre- and post- deploy hooks are just great. Thank's a lot!

**Comment by banago** [comment]
Cool beans! Thanks for your feedback.

**Comment by banago** [comment]
Everyone, PHPloy 4.0 stable is out and up for grabs.

Enjoy! :fireworks:
