### ISSUE TITLE
Revision not set correctly when rolling back

### ISSUE THREAD

**Issue by GuidoHendriks** [banago/PHPloy#84]
When rolling back to a previous commit, it doesn't write the correct hash to `.revision` on the server. It seems like the `setRevision` method only deals with deploys and syncs, not rollbacks?

**Comment by banago** [comment]
Did you test it? I haven't experienced that behavior before.

**Comment by GuidoHendriks** [comment]
Yes, I just tried it. After rolling back, the hash in `.revision` didn't change. Should've been the hash from the commit it rolled back to, right? I actually spotted it in code. It uses `localRevision` as hash to set, but that's never the right value when rolling back.

**Comment by banago** [comment]
Yes, that's right, it should save the has from the commit. Thanks for pointing this out. Would you like to fix this too?
