### ISSUE TITLE
Applying $filesToIgnore on files to delete

### ISSUE THREAD

**Issue by GuidoHendriks** [banago/PHPloy#88]
When rolling back after creating files, it tries to delete the files on the server. If one of the files created in the last commit is in `$filesToIgnore`, it still tries to delete that file. That fails because it wasn't uploaded to the server in the first place.

**Comment by banago** [comment]
Right now, when it fails to delete it throws an exception too, which should not happen since it stops the deployment and it should not happen. I hope to enhance this part on v4. For now let's fix what you are describing. Great catch.

**Comment by banago** [comment]
@GuidoHendriks normal deployment is broken.  I don't know which pull caused it, but now a fresh deploy happens everytime I try to deploy.

**Comment by banago** [comment]
Never mind - seems an issue on my end.

**Comment by GuidoHendriks** [comment]
@banago I'm on it.

**Comment by banago** [comment]
Confirmed: After deployment the revision is not updated in server.

**Comment by GuidoHendriks** [comment]
@banago I screwed up in my attempt to "Keep it dry" in #91. Fix is on the way.

**Comment by GuidoHendriks** [comment]
#93 should fix it. Will test more thoroughly in the future.

**Comment by banago** [comment]
Just tested - seems all good for now. Great job!
