### ISSUE TITLE
Count of files to upload and deleted files

### ISSUE THREAD

**Issue by GuidoHendriks** [banago/PHPloy#89]
What should be the correct way to count files to upload and files to delete?

Currently, when adding 2 files and deleting 1 this is what happens:

    removed 1 of 3 .DS_Store
     ^ 1 of 3 .gitignore
     ^ 2 of 3 bar

I think this should either be:

    removed 1 of 1 .DS_Store
     ^ 1 of 2 .gitignore
     ^ 2 of 2 bar

Or: 

    removed 1 of 3 .DS_Store
     ^ 2 of 3 .gitignore
     ^ 3 of 3 bar

I think the first option is the best.

**Comment by banago** [comment]
I agree, we should count them separately.
