### ISSUE TITLE
PHPloy 3 stable release?

### ISSUE THREAD

**Issue by GuidoHendriks** [banago/PHPloy#95]
By now there's a 3.0.15-stable tag. But after that revision there has been some bug fixes already, a few of them by myself. With that in mind, I wouldn't actually call the 3.0.15 tag stable.

Maybe we should do a proper 3 release after the current code is tested thoroughly by everyone?

**Comment by GuidoHendriks** [comment]
I actually tested the current code with good results. Except for the submodules, which I didn't test at all.

**Comment by banago** [comment]
With your fixes, it will be v3.0.16-stable. It's OK that the previous had some little bugs; we've got to be consistent with tagging.
