### ISSUE TITLE
Explicitly include files excluded by .gitignore?

### ISSUE THREAD

**Issue by SamHH** [banago/PHPloy#96]
There are some directories/files I would like to not be tracked by Git, but still uploaded to the server (e.g. img/ folder). Is there any way to do this? If not, is it possible that this could be added similarly to skip[] in deploy.ini?

Thanks!

**Comment by GuidoHendriks** [comment]
Since those files aren't tracked by Git, you cannot check the state on the servers. My suggestion would be either adding those to Git anyway or handle files like that manually.

**Comment by banago** [comment]
@SamHH please check out the `--other` parameter here: https://github.com/banago/PHPloy#upload-other-files

**Comment by SamHH** [comment]
@banago So with that I could feasibly exclude whatever I need from Git with .gitignore, then use deploy.ini to exclude whatever I need from the server (including manually replicating whatever is in .gitignore)?

**Comment by banago** [comment]
@SamHH yes sir  -- we have the `skip[]` for this purpose. Check the sample `deploy.ini` file.

**Comment by SamHH** [comment]
Oh that's lovely.

Thanks!
