### ISSUE TITLE
Default server

### ISSUE THREAD

**Issue by NathanGiesbrecht** [banago/PHPloy#97]
I think it would be great if the default action was, instead of deploying to all configured servers, if there was the option of having a [default] server which would be the only one deployed to if the program was run with no parameters. 

For example, my work flow is I do work, then upload to a staging server for further "real world" testing before actually deploying to production. Which requires me to `phploy -s staging` and once that's good to go I do `phploy` to deploy to production. This makes me nervous because I may accidentally deploy to production if I don't specify a parameter.

Just from a save-me-from-screwing-up standpoint, does anybody else think this is a good idea? If so, I'd be happy to help in making the changes.

**Comment by GuidoHendriks** [comment]
I agree that deploying to all servers by default might not be the best option. Because of this I wrote a wizard, which gives us all the options. Maybe this is an option as a default, with parameters as a shortcut to a specific action.

**Comment by banago** [comment]
@NathanGiesbrecht we had another guy request this exact feature and I closed it since I thought we have already in place what we need with specifying a server. But I do get where you come from with the fear of messing up and deploying to all servers. So, let's do it. You have green light to build this feature and I'll merge with with pleasure. Thanks for taking the time to create this issue.

**Comment by NathanGiesbrecht** [comment]
Great. I'll get on it this weekend. What I was thinking was have a [default] server, and then to deploy to all implementing a --all flag, or something to that effect? Sound reasonable?

**Comment by banago** [comment]
Yes, sounds great. Looking forward to your pull request. :)

**Comment by NathanGiesbrecht** [comment]
https://github.com/banago/PHPloy/pull/99

**Comment by banago** [comment]
This is not merged - thanks @NathanGiesbrecht. You have the honor to close this issue. :smile:

**Comment by NathanGiesbrecht** [comment]
My pleasure @bango I'll try to take a look at some of the other issues when I have time. This tool is saving me tonnes of stress lately.
