### ISSUE TITLE
Run Phploy on Windows

### ISSUE THREAD

**Issue by Threeeagle** [banago/PHPloy#98]
Dear all, 

having big trouble getting phploy to work on my windows machine. 
Neither from Git Bash, nor Windows CMD. 

Using Git 1.9.5 (latest stable windows), PHPloy 3 (tried with Version 2 as well, got different errors), PHP 5.4 (tried with 5.6 as well)

Errors in PHPloy 3:
Git Bash error: Trying two calls: 

![phploy1](https://cloud.githubusercontent.com/assets/11395033/6561806/54edf5d6-c694-11e4-9872-a0f423e50d04.png)

CMD:

![image](https://cloud.githubusercontent.com/assets/11395033/6561662/4804ee8e-c693-11e4-9e3f-1265c9087eb3.png)

Guess it has to do with wrong escaping / usage of Slashes and Backslashes

Different Error in PHPloy2:
![image](https://cloud.githubusercontent.com/assets/11395033/6561732/c57ec16e-c693-11e4-89db-71ebbc7f59ac.png)

Here the carets come from escapecmd() however, even without this call it doesnt work.

Here is my System-Path:
C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\dev\tools\nodejs\;C:\dev\tools\php\php54;C:\dev\tools\phploy2;C:\Program Files (x86)\Git\bin

Would highly appreciate your answer... 

BR

**Comment by banago** [comment]
@SimonEast could you have a look at this. What seems to be the problem here?

**Comment by SimonEast** [comment]
I'm pretty flat-out at the moment so don't have heaps of time to investigate, but here's a couple thoughts:

* Not sure if you can run BAT files from git bash.  Does that normally work?  Perhaps you can just call `php.exe phploy` and bypass the BAT?
* In the 2nd error, it appears to be unable to find autoload.php, but I don't think the slashes are an issue.  I normally use forward slashes in PHP on Windows and it normally works fine.  Have you done your `composer install` successfully?
* I think the caret `^` escaping possibly looks OK.  What happens if you just run that git command directly from the command prompt?

        git --git-dir=^"C:^\dev^\repositories^\YourScorez/.git^" --work-tree=^"C:^\dev^\repositories^\YourScorez^" submodule status

**Comment by Threeeagle** [comment]
Hi Simon,

thank you for your answer.

1) If I bypass the bat in git-bash I get the "error loading autoload.php:
![image](https://cloud.githubusercontent.com/assets/11395033/6768481/fe9ba41a-d06d-11e4-8ba6-58c0a6bcc111.png)

2) not sure about composer. Installed just php. I composer required?

3) This one also fails with a somewhat unclear error to me:
![image](https://cloud.githubusercontent.com/assets/11395033/6768488/608bdf82-d06e-11e4-8955-dbd01a7f2f8e.png)

...

**Comment by NathanGiesbrecht** [comment]
I get these same errors if I try running it without running composer install first. You need to download and install composer, and then run "composer install" inside the PHPloy directory. This will download and install the dependencies. This should probably be clarified in install instructions.

**Comment by banago** [comment]
That's right.Most people use the .phar file thought that is on bin folder
and that has everything packed.

**Comment by Threeeagle** [comment]
Oh damn true, perfect, thank you. fixed.

**Comment by banago** [comment]
@Threeeagle very happy you figured this out.
